### PR TITLE
Simple dependency injection for backend tables

### PR DESCRIPTION
**Pull request by Naburimannu**
Allows us to call different constructors during testing instead of relying on actual on-filesystem databases. This strawman proposal puts all backends' factories on the same class; they could be backend-specific for easier code reading

Addresses https://github.com/ga4gh/server/issues/82.

### CODE REVIEW

**Comment by Naburimannu** [comment]
@dcolligan @jeromekelleher I think this is what @kerrydc was getting at, but he's traveling in California this week.

**Comment by pashields** [comment]
@Naburimannu you have some pep8 issues

This does solve the issue kerry and I were discussing that led to the slightly underspecified #82. Kerry was trying avoid creating actual on disk files for tabix testing. I believe this will take care of that. I don't think this mutually exclusive with what @dcolligan is arguing for. Perhaps more importantly, it's a fine step in the right direction.

I'll +1 this even without splitting it out because it's useful now.

**Comment by Naburimannu** [comment]
Fixed PEP8.

**Comment by Naburimannu** [comment]
Thanks for the +1, @pashields , but this really was a strawman - it's not actually integrated, and I don't  think it can be made to work with cli and backend as currently written. We need to move the entire directory traverse out of Backend.__init__() to allow non-filesystem ways of setting up backends.

@dcolligan, I think @pashields is right that you and I are solving different problems with our changes.

**Comment by dcolligan** [comment]
@Naburimannu Yes, I think we're all agreed that our changes are orthogonal.

**Comment by kerrydc** [comment]
+1 to this approach, it is indeed what I was getting at.

**Comment by jeromekelleher** [comment]
OK, let's bring this up to date and merge then. Can you rebase please @Naburimannu?

**Comment by jeromekelleher** [comment]
Do you want to bring this up to date and re-review @Naburimannu, or should we close this PR?

**Comment by Naburimannu** [comment]
I should be able to readdress this Friday.

**Comment by Naburimannu** [comment]
I think this is the right way forward, but I've not been able to work on it in too long. Closing the PR; somebody else can feel free to do the work, or I'll circle back on it when I have the opportunity.

**Pull request closed without merging**
