### PR TITLE
refactoring frontend endpoints

### PR DESCRIPTION
**Pull request by MollyZhang**
#143

### CODE REVIEW

**Comment by Naburimannu** [comment]
+0

Good idea, and the code looks fine to me.

However, I'd like to see more meaningful commit messages so somebody reading the git repository can understand your change. If I'm reading github correctly, there's absolutely no prose connected to this commit.

**Comment by dcolligan** [comment]
@Naburimannu the commit message seems to be "refactoring frontend endpoints" ... check out the commits tab of this PR (or look at this tab's links to the commit).  I think that's a fine commit message (maybe the one thing I would add is the issue number, but I realize that not everyone agrees on that convention).

**Comment by jeromekelleher** [comment]
+1 (once CI completes).

The commit message is fine here, but we should have more meaningful messages in the PR description. It doesn't take long to write a couple of sentences, and it's a big help to reviewers.

**Comment by jeromekelleher** [comment]
Update --- CI seems to be failing because of problems with the new version of Pysam. I've created an (issue)[https://github.com/pysam-developers/pysam/issues/79].

**Comment by jeromekelleher** [comment]
The pysam issue has been resolved. The Travis build for this should be restarted once #156 has been merged.

**Comment by dcolligan** [comment]
+1 after rebasing and tests pass

**Comment by jeromekelleher** [comment]
The travis build is passing, so all is good. There's no need to rebase here as the changes are simple and localised. Thanks @MollyZhang.

**Pull request merged**
