### PR TITLE
Fixed reference name parsing bug

### PR DESCRIPTION
**Pull request by macieksmuga**
References with dots in their name were crashing the server.

### CODE REVIEW

**Comment by kozbo** [comment]
+1 I tried out this change and it fixed the problem for my server using data from the 1000 Genome data reference set.

**Comment by dcolligan** [comment]
-1 we should solve this at a more general level

see the current repo manager's methods ... perhaps some of those can be refactored out into a path handling library

**Comment by macieksmuga** [comment]
@dcolligan this will be moot once we move to SQL-based server resource management, which is the correct fix. Until then, this is a trivial 1-line fix that actually prevents a server crash on the full GRCh37 reference. Please reconsider.

**Comment by diekhans** [comment]
we need to solve this on a pragmatic level *now*

**Comment by dcolligan** [comment]
Alright, I'll rescind my -1 as long as a bug gets created for the more general issue (some intelligent solution to path/extension handling)

**Comment by macieksmuga** [comment]
Thanks @dcolligan! Created: #1087 to capture this.

**Comment by jeromekelleher** [comment]
+1 --- I agree it's a hacky fix, but the general solution is on its way.

**Pull request merged**
