### PR TITLE
Bugfix release

### PR DESCRIPTION
**Pull request by dcolligan**
- Bump to version ~~0.1.0~~ 0.1.1
- Refactor and test backend generators
- Take out unused paths
- added sphinx exception to gitignore

#391

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Thanks for this @dcolligan. Some minor issues:

1. I think we should make a release of 0.1.0 first where all we do is bump the version number. This is our real 'initial' release, which we have for archival purposes. The release that you're making here will then be 0.1.1, the first bugfix release.
2. Is it possible to pull in the original commits into the PR where the work was done, and not just all of them squashed together? I think it'll be hard to keep track of what's gone into the release branch if we don't do this.

**Comment by dcolligan** [comment]
@jeromekelleher Ok, I changed the version number here to 0.1.1.  I suppose it is possible to separate out the commits here, but I don't see much point in that.  They have different commit shas than the cherry-picked commits both because the commit history they are working off is different and the cherry-picks weren't clean and I needed to resolve some conflicts manually.  I listed the commits in `server/develop` that I cherry picked in the commit message, which hopefully will satisfy you.  I also submitted a new PR for the 0.1.0 version bump here: https://github.com/ga4gh/server/pull/413

**Comment by jeromekelleher** [comment]
Looks good, thanks @dcolligan. Good git-fu on pulling out the commits and documenting their source.

One last point: shouldn't we be making these pull requests against the 0.1-release branch rather than stable? The idea is we can make more and smaller commits onto the release branch, and then tag from there. We only merge back to `stable` after the release is made and we're fully happy everything works.

**Comment by dcolligan** [comment]
If there were multiple contributors that needed to commit code over time to a release branch, then yes, it would make sense to commit against 0.1-release.  But as it stands, we're only putting one commit into stable and I'm the only author, so I don't think it makes that much difference.

**Comment by jeromekelleher** [comment]
OK, fair enough. I would prefer to see this done on a release branch in future, but you're right that it makes no difference now. I'm think we should merge this and release it, as soon as the 0.1.0 has been pushed to PyPI.

+1.

**Comment by dcolligan** [comment]
Ok, 0.1.0 has been uploaded to pypi... this can be merged now

**Comment by jeromekelleher** [comment]
Merged, thanks @dcolligan. Great work on the git-foo. Fancy rolling the 0.1.1 release from this (pypi + github)?

**Comment by dcolligan** [comment]
Done and done
https://github.com/ga4gh/server/releases/tag/v0.1.1
https://pypi.python.org/pypi/ga4gh/0.1.1

**Comment by jeromekelleher** [comment]
Superb!

**Pull request merged**
