### PR TITLE
Increase required test coverage to 90%

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #195

### CODE REVIEW

**Comment by dcolligan** [comment]
Huh, this is strange... coverage numbers are different on my local machine than in Travis.

Local:
```
$ python scripts/run_tests.py
*** Running: "flake8 tests ga4gh scripts"
*** Running: "nosetests --with-coverage --cover-package ga4gh --cover-inclusive --cover-min-percentage 90"
..................................................................................
Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
ga4gh                             1      0   100%
ga4gh._protocol_definitions     603     20    97%   38-39, 72-73, 111, 156, 251, 281, 312, 916, 996, 1104, 1216-1217, 1301-1302, 1379-1380, 1467-1468
ga4gh.backend                   138      1    99%   50
ga4gh.backend_exceptions         14      0   100%
ga4gh.cli                       432      0   100%
ga4gh.client                    122      1    99%   56
ga4gh.converters                 17      4    76%   15-16, 28, 40
ga4gh.datamodel                   3      0   100%
ga4gh.datamodel.reads            33     20    39%   22-32, 38-43, 53-54, 60-63
ga4gh.datamodel.references       31     18    42%   24-35, 41-44, 55-56, 62-65
ga4gh.datamodel.variants        224     32    86%   320-322, 324-325, 328, 335-340, 342-344, 346, 348-353, 361-371, 375-376
ga4gh.frontend                  123      0   100%
ga4gh.frontend_exceptions        74      0   100%
ga4gh.protocol                   70      7    90%   20-23, 34, 50, 120
ga4gh.serverconfig                7      0   100%
-----------------------------------------------------------
TOTAL                          1892    103    95%
----------------------------------------------------------------------
Ran 82 tests in 14.565s

OK
*** SUCCESS
```

Travis:
```
[0Ktravis_time:start:201c2fa4
[0K$ flake8 tests ga4gh scripts
travis_time:end:201c2fa4:start=1425049615745792604,finish=1425049616353068292,duration=607275688
[0K
[32;1mThe command "flake8 tests ga4gh scripts" exited with 0.[0m
travis_time:start:1f6116fc
[0K$ nosetests --with-coverage --cover-package ga4gh --cover-inclusive --cover-min-percentage 90
..................................................................................
Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
ga4gh                             1      0   100%   
ga4gh._protocol_definitions     603     44    93%   38-39, 72-73, 111-112, 156-157, 251-252, 281-282, 311-312, 346-347, 432-433, 464-465, 502-503, 536-537, 821-822, 874-875, 916-917, 995-996, 1104-1105, 1216-1217, 1301-1302, 1379-1380, 1467-1468, 1697-1698
ga4gh.backend                   138     15    89%   39-43, 49-52, 82, 121, 131, 141, 151, 210, 218
ga4gh.backend_exceptions         14      0   100%   
ga4gh.cli                       432    104    76%   28-40, 50-73, 100-105, 131, 133, 135, 169, 234, 245-248, 279-280, 306-312, 325, 338-341, 347-352, 358-370, 383, 396, 409, 422, 435-440, 448, 462-464, 475, 486, 496-512, 767, 788-789
ga4gh.client                    122     14    89%   39, 51, 56, 71, 75-77, 81-83, 87, 91-93, 112
ga4gh.converters                 17      6    65%   15-16, 24, 28, 36, 40
ga4gh.datamodel                   3      0   100%   
ga4gh.datamodel.reads            33     20    39%   22-32, 38-43, 53-54, 60-63
ga4gh.datamodel.references       31     18    42%   24-35, 41-44, 55-56, 62-65
ga4gh.datamodel.variants        224     51    77%   195, 199, 221-224, 230-231, 249-260, 269, 320-328, 335-353, 361-371, 375-376
ga4gh.frontend                  123      9    93%   39, 42, 93, 95, 141, 162, 178, 183, 211
ga4gh.frontend_exceptions        74      0   100%   
ga4gh.protocol                   70      7    90%   20-23, 34, 50, 120
ga4gh.serverconfig                7      0   100%   
-----------------------------------------------------------
TOTAL                          1892    288    85%   
nose.plugins.cover: ERROR: TOTAL Coverage did not reach minimum required: 90%
travis_time:end:1f6116fc:start=1425049616361278970,finish=1425049637476614504,duration=21115335534
[0K
[31;1mThe command "nosetests --with-coverage --cover-package ga4gh --cover-inclusive --cover-min-percentage 90" exited with 1.[0m

Done. Your build exited with 1.
```
Can someone else report their local coverage numbers, to see if it's just a problem with my local environment?

**Comment by macieksmuga** [comment]
FWIW, here are the coverage test results from my local environment.

```
(testenv3)dhcp-59-193:maciek-ga4gh-server maciek$ python scripts/run_tests.py 
*** Running: "flake8 tests ga4gh scripts"
*** Running: "nosetests --with-coverage --cover-package ga4gh --cover-inclusive --cover-min-percentage 80"
..................................................................................
Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
ga4gh                             1      0   100%   
ga4gh._protocol_definitions     603     20    97%   38-39, 72-73, 111, 156, 251, 281, 312, 916, 996, 1104, 1216-1217, 1301-1302, 1379-1380, 1467-1468
ga4gh.backend                   138     11    92%   39-43, 49-52, 131, 210, 218
ga4gh.backend_exceptions         14      0   100%   
ga4gh.cli                       432     38    91%   28, 39, 56, 65, 69-73, 100, 131, 133, 135, 248, 279-280, 339-341, 350-352, 358-366, 370, 383, 439-440, 463-464, 475, 504-505, 767, 788-789
ga4gh.client                    122      5    96%   51, 56, 82-83, 87
ga4gh.converters                 17      6    65%   15-16, 24, 28, 36, 40
ga4gh.datamodel                   3      0   100%   
ga4gh.datamodel.reads            33     20    39%   22-32, 38-43, 53-54, 60-63
ga4gh.datamodel.references       31     18    42%   24-35, 41-44, 55-56, 62-65
ga4gh.datamodel.variants        224     50    78%   195, 199, 221-224, 230-231, 249-260, 269, 320-325, 327-328, 335-353, 361-371, 375-376
ga4gh.frontend                  123      6    95%   93, 95, 141, 178, 183, 211
ga4gh.frontend_exceptions        74      0   100%   
ga4gh.protocol                   70      7    90%   20-23, 34, 50, 120
ga4gh.serverconfig                7      0   100%   
-----------------------------------------------------------
TOTAL                          1892    181    90%   
----------------------------------------------------------------------
Ran 82 tests in 11.459s

OK
*** SUCCESS
```

**Comment by dcolligan** [comment]
@macieksmuga is that from the latest master?

**Comment by macieksmuga** [comment]
@dcolligan Yep. I updated my local repo and rebuilt the code a minute before running it.

**Comment by dcolligan** [comment]
I thought the `--cover-inclusive` flag might have been the culprit, but that doesn't seem to be it.  Here's that run on Travis:
```
$ nosetests --with-coverage --cover-package ga4gh --cover-min-percentage 90
..................................................................................
Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
ga4gh                             1      0   100%   
ga4gh._protocol_definitions     603     44    93%   38-39, 72-73, 111-112, 156-157, 251-252, 281-282, 311-312, 346-347, 432-433, 464-465, 502-503, 536-537, 821-822, 874-875, 916-917, 995-996, 1104-1105, 1216-1217, 1301-1302, 1379-1380, 1467-1468, 1697-1698
ga4gh.backend                   138     15    89%   39-43, 49-52, 82, 121, 131, 141, 151, 210, 218
ga4gh.backend_exceptions         14      0   100%   
ga4gh.cli                       432    104    76%   28-40, 50-73, 100-105, 131, 133, 135, 169, 234, 245-248, 279-280, 306-312, 325, 338-341, 347-352, 358-370, 383, 396, 409, 422, 435-440, 448, 462-464, 475, 486, 496-512, 767, 788-789
ga4gh.client                    122     14    89%   39, 51, 56, 71, 75-77, 81-83, 87, 91-93, 112
ga4gh.converters                 17      6    65%   15-16, 24, 28, 36, 40
ga4gh.datamodel                   3      0   100%   
ga4gh.datamodel.reads            33     20    39%   22-32, 38-43, 53-54, 60-63
ga4gh.datamodel.references       31     18    42%   24-35, 41-44, 55-56, 62-65
ga4gh.datamodel.variants        224     51    77%   195, 199, 221-224, 230-231, 249-260, 269, 320-328, 335-353, 361-371, 375-376
ga4gh.frontend                  123      9    93%   39, 42, 93, 95, 141, 162, 178, 183, 211
ga4gh.frontend_exceptions        74      0   100%   
ga4gh.protocol                   70      7    90%   20-23, 34, 50, 120
ga4gh.serverconfig                7      0   100%   
-----------------------------------------------------------
TOTAL                          1892    288    85%   
nose.plugins.cover: ERROR: TOTAL Coverage did not reach minimum required: 90%
```

**Comment by dcolligan** [comment]
Ok, figured out what the problem was.  See: #197  Fix will be in a PR shortly.

This PR can just sit here until we increase our coverage numbers, which are at 85% presently.

**Pull request closed without merging**
