### PR TITLE
Fill out ReadGroup.toProtocolElement...

### PR DESCRIPTION
**Pull request by dcolligan**
... to the extent that we can, which is not much

Issue #242

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Does this pass validate()? We should add some data driven tests to exercise this.

**Comment by dcolligan** [comment]
I'm adding those tests in the other PR

**Comment by jeromekelleher** [comment]
OK, let's merge this so.

+1.

**Comment by dcolligan** [comment]
@jeromekelleher merge me!

**Pull request merged**
