### PR TITLE
Document long running branch workflow

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #849

### CODE REVIEW

**Comment by jeromekelleher** [comment]
+1

**Comment by dcolligan** [comment]
@jeromekelleher don't merge this until I update it with what (I think?) we've resolved about long-running branches:

- host long running branches are hosted in the ga4gh/server repo
- long running branches are protected
- branch manager may update topic branch as frequently as possible
- updates must be done to topic branches via PRs, so that Travis runs

Did I miss anything?

**Comment by jeromekelleher** [comment]
That about covers it @dcolligan, thanks.

**Comment by dcolligan** [comment]
@jeromekelleher updated

**Comment by jeromekelleher** [comment]
+1.

**Comment by dcolligan** [comment]
@jeromekelleher merge me!

**Pull request merged**
