### PR TITLE
Issue221

### PR DESCRIPTION
**Pull request by shajoezhu**
resolving issue #221

### CODE REVIEW

**Comment by shajoezhu** [comment]
still working on this, an update is coming soon

**Comment by shajoezhu** [comment]
hi @jeromekelleher, i think this is ready to be merged in to the master, all tests and validation are passing

**Comment by jeromekelleher** [comment]
Something's gone a bit weird here @shajoezhu --- can you rebase this off upstream/master please?

**Comment by shajoezhu** [comment]
sorry @jeromekelleher , had some problem with merging, and did something wrong, i have created an separate branch regarding to issue #221, and submitted a new pull request #264.

**Pull request closed without merging**
