### PR TITLE
add coverage package!

### PR DESCRIPTION
**Pull request by jsh2134**
via https://github.com/ga4gh/server/issues/723

### CODE REVIEW

**Comment by jsh2134** [comment]
:( test failed. looks like the build wheel needs to be regenerated or something

**Comment by jeromekelleher** [comment]
Looks like we need something more specific (see the travis log).

**Comment by dcolligan** [comment]
is this the right package?

**Comment by jsh2134** [comment]
looks like that package is already in the requirements file....i didn't even notice. thats why it failed....running with the existing version and the flag `cover-min-percentage` works fine on my machine.

closing...

```
nosetests -vs --with-coverage --cover-min-percentage=10 --cover-package=ga4gh.datamodel.variants tests/unit/test_variants.py
testGenotypeHaploid (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypePhasedAltAlt (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypePhasedDiffAlt (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypePhasedFirstHalfCall (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypePhasedNoCall (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypePhasedRefAlt (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypePhasedRefRef (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypePhasedSecondHalfCall (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypeUnphasedAltRef (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypeUnphasedFirstHalfCall (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypeUnphasedNoCall (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypeUnphasedRefAlt (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypeUnphasedRefRef (tests.unit.test_variants.TestGenotypes) ... ok
testGenotypeUnphasedSecondHalfCall (tests.unit.test_variants.TestGenotypes) ... ok
testPhasesetZero (tests.unit.test_variants.TestGenotypes) ... ok

Name                       Stmts   Miss  Cover   Missing
--------------------------------------------------------
ga4gh.datamodel.variants     287    188    34%   46, 62-70, 76, 98, 104, 161-162, 175-179, 187-190, 197-199, 220-228, 231, 234-236, 239-244, 248-256, 265-291, 295-298, 306, 315-320, 328-333, 341, 349-357, 361, 364-379, 382-411, 419-448, 451-468, 476-491, 494, 506-540
----------------------------------------------------------------------
Ran 15 tests in 0.005s

OK
```

**Pull request closed without merging**
