### PR TITLE
Bump version to 0.1.0

### PR DESCRIPTION
**Pull request by dcolligan**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Following the discussion on #410, I think we should merge this and push the resulting release to PyPI. @dcolligan, would you like to do the honours?

+1.

**Comment by dcolligan** [comment]
Alright, I uploaded 0.1.0 to pypi

**Comment by jeromekelleher** [comment]
Excellent - can we tag this in github as well please?

**Comment by dcolligan** [comment]
Done https://github.com/ga4gh/server/releases/tag/v0.1.0

**Comment by jeromekelleher** [comment]
Excellent! Thanks @dcolligan.

**Pull request merged**
