### PR TITLE
Minimum patching up to make tabix backend work.

### PR DESCRIPTION
**Pull request by jeromekelleher**
The TabixVariantSet is currently broken (not surprisingly since we have no test coverage...). This PR is the minimum required to make it operational.

### CODE REVIEW

**Comment by dcolligan** [comment]
How about adding a test to ensure we don't regress?

**Comment by jeromekelleher** [comment]
It would be nice @dcolligan, but it's not trivial (otherwise it would already be done) and I don't have time to do it now. The Tabix backend is currently broken (so people can't use it) and this fixes it back to where it was.

**Comment by jeromekelleher** [comment]
@dcolligan, any chance of a +1 and merge here? I've got a proposal for fixing testing on the TabixBackend in #208, which we'll need to discuss for a while. Can we merge this fix the breakage for the moment?

**Comment by dcolligan** [comment]
+1 merging

**Pull request merged**
