### PR TITLE
Fixes import issue for tests utils.

### PR DESCRIPTION
**Pull request by jeromekelleher**
This fixes an issue in which `tests/test_backends.py` ERRORed when run in isolation using
```
nosetests -vs tests/test_backends.py
```

### CODE REVIEW

**Comment by dcolligan** [comment]
That's weird... do you have an explanation of why this would break before this patch and how this patch fixes it?

**Comment by dcolligan** [comment]
Oh, I see... nevermind.  Can you also fix this in other tests, too (even if it is a question of consistent style)?  Check out `test_schemas.py`

**Comment by jeromekelleher** [comment]
Done - thanks for pointing this one out. To answer your question, I don't really have an explanation. Luckily, the method that works happens to follow our preferred style, so all is good.

**Comment by Naburimannu** [comment]
+1

**Pull request merged**
