### PR TITLE
Refactor of ReadAlignmentCompoundId

### LINKED ISSUE #596: SearchReads accepts only one ReadGroup ID, contrary to schema
The schemas say that `SearchReadsRequest` accepts *at least* one ReadGroup ID, but the ref server accepts *at most* one.

```avro
record SearchReadsRequest {
   /**
   The ReadGroups to search. At least one readGroupId must be specified.
   */
   array<string> readGroupIds;
   ...
}
```

This test case is from a forthcoming compliance test, `ReadsSearchIT.searchReadsWithAllIdsReturnsReadsForEach`:

```java
threeReadGroupIds = getThreeReadGroupIdsSomehow(); // details omitted (obviously :-))
SearchReadsRequest request =
                SearchReadsRequest.newBuilder()
                                  .setReadGroupIds(threeReadGroupIds)
                                  .setStart(0L)
                                  .setEnd(150L)
                                  .setReferenceId(refId)
                                  .build();
SearchReadsResponse response = client.reads.searchReads(request);
```

The call to `searchReads` throws a `GAException`:

`{"errorCode":1151425451,"message":"Exactly one read group id must be specified"}`

with HTTP status `501` (`NOT_IMPLEMENTED`).

This is contrary to the comments in the schema, not to mention that the declaration of the `readGroupIds` field is `array<string>`, not a single `string`.

### PR DESCRIPTION
**Pull request by dcolligan**
Remove readGroupId portion of RACID

Does not close #596 

See discussion in #1021

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good. Just so we can see what's happening, can you show a couple of examples of what these look like (unobfuscated)?

Are these unique for the simulator?

**Comment by dcolligan** [comment]
Example readId: `'1kg-p3-subset:HG00096:SRR062634.8799468'`

**Comment by dcolligan** [comment]
I'm not sure about the read simulator.  It seems good enough for now though (the readId keeps incrementing).  We can revisit this later if there is a strong requirement for unique read ids across readGroups during simulation.

**Comment by dcolligan** [comment]
Some simulated readIds:
```
'simulatedDataset0:simRgs0:simulated18'
'simulatedDataset0:simRgs0:simulated73'
```

**Comment by jeromekelleher** [comment]
It shouldn't be hard to do I think, just munge the readGroupId into the readId. I think this will bite us at some point if we don't make sure simulated IDs are unique.

**Comment by dcolligan** [comment]
@jeromekelleher updated... simulated read Ids now look like:
```
'simulatedDataset0:simRgs0:rg0$simulated18'
'simulatedDataset0:simRgs0:rg0$simulated73'
```

**Comment by jeromekelleher** [comment]
Excellent, thanks. +1.

**Comment by diekhans** [comment]
note that the field Read.id is not defined in the same way as
other ids; it is local to the ReadGroupSet.  I will file a
ticket to get it renamed.

**Comment by jeromekelleher** [comment]
Looks like no objections; can you update and merge please @dcolligan?

**Pull request merged**
