### PR TITLE
Consolidate hardcoded test values

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #557

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I'm afraid I don't really see the point of this --- we should be adding methods to get these values in the places we're using them, and generalising away from using hardcoded values. This just centralises all the hardcoded values, and doesn't address the underlying bad practices. 

I've refactored out the hard coded values from ``test_simulated_stack.py``, and it wouldn't be hard to do the same for the others I think.

**Comment by diekhans** [comment]
I dislike `utils.Hardcoded' (anything called utils or common doesn't
aid in the understanding of code.  Call a class Hardcoded kind of just
makes it sounds bad.  It's really static configuration, right?

What is a better approach?  While I agree having static
configuration scattered around the code isn't that great, I have
also seen people go to such great lengths to avoid being accused
of hardcoding stuff that they make things much worth.  Things
like multiple level of indirection to get variables out of
non-code text files that are tightly bound to the code are no
better than `hardcoding'.

The best luck I have had is having functions to get
configuration values, a lot of just static configuration values.

**Comment by jeromekelleher** [comment]
These are really just ID values that we can discover at run time. I think it'll be easy to instantiate a backend, and find the values we want in the majority of cases.

**Comment by diekhans** [comment]
As long as this doesn't create the danger of missing test because
test data is missing, sounds like a very sane approach ..

ok, I am going back to the peanut gallery ..

**Comment by jeromekelleher** [comment]
Yeah, good point --- always check ``len(testObjects) > 0`` before starting the test!

**Comment by dcolligan** [comment]
@jeromekelleher so what interface would you favor for this?  A classmethod on every simulated class to generate an id (given a counting variable which defaults to 0)?  Or just one object in `datasets/__init__` which generates ids given a class?  etc.

**Comment by jeromekelleher** [comment]
I think we can just do something like
```python
backend = self._app.backend
dataset = backend.getDatasets()[0]
variantSet  = dataset.getVariantSets()[0]
self._datasetId = dataset.getId()
self._variantSetId = variantSet.getId()
```
in setup and then use ``self._variantSetId`` etc where we need ID values. Something like this will definitely work for `test_views.py`, which is currently the worst offender. It's a little more complicated for the end-to-end tests, I agree, but these can be dealt with too I'm sure.

**Comment by dcolligan** [comment]
@jeromekelleher alright, pushed an update... just consolidated the ids for the end to end tests, but took your advice on the rest

**Comment by jeromekelleher** [comment]
Superb, thanks for this @dcolligan! I was just about to hit off the hard-coded IDs in ``test_views`` and you saved me.

+1

**Pull request merged**
