### PR TITLE
Changed the input data format for consistency.

### PR DESCRIPTION
**Pull request by jeromekelleher**
After starting to document the input data format, I realised that it was very confusing and inconsistent. This PR makes datasets and referencesets symmetrical and treated in the same way.

The input data directory must now be in the following format:

```
dataDir/
    datasets/
        dataset1
            /variants
            /reads
        dataset2
            #etc
    referenceSets
        referenceSet1/
        referenceSet2/
```
Datasets and ReferenceSets are now treated symmetrically (other than their annoying spelling difference...).

This is a breaking change, and will affect all users. It is better to get this change out of the way before we start the release process though.

### CODE REVIEW

**Comment by dcolligan** [comment]
+1

**Comment by dcolligan** [comment]
(after the tests are fixed, of course!)

**Comment by jeromekelleher** [comment]
Thanks @dcolligan, fixed the issue.

**Comment by hjellinek** [comment]
Hi @jeromekelleher - don't forget to `@`-mention us (@macieksmuga and @hjellinek) on changes that can affect the compliance data, so we can prepare.

This one caught us with our trousers descended. :-)  Thanks.

**Comment by jeromekelleher** [comment]
Oops, sorry @hjellinek, my bad.

**Comment by macieksmuga** [comment]
@jeromekelleher I updated #656 to comply with this new format.

**Pull request merged**
