### PR TITLE
Only log exceptions if they are true server errors

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #1151

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Very tidy, thanks. Can you confirm that this cleans up the nosetests output?

**Comment by dcolligan** [comment]
@jeromekelleher yep it does

**Comment by jeromekelleher** [comment]
Great, +1.

@kozbo, are you happy with this change? This should mean that only genuine errors end up in the Apache error log as a stack trace. Normal user input errors should come up in error.log as a single line (indicating that they've been handled normally).

**Comment by kozbo** [comment]
Yes, this seems like a very clean solution.

**Comment by david4096** [comment]
+1 Yeah, this is annoying. I've been looking at a lot of logs lately and the error logs will be cleaner. It would be great to be able to log those messages elsewhere as they are still useful but not "errors". Could you also check if the test_request_context removes the request path? The messages say they were from requests pointed at /GET, when I don't believe they are:

```
[Wed Apr 27 04:33:05.014055 2016] [:error] [pid 13825:tid 139644394280704] Exception on / [GET]
[Wed Apr 27 04:33:05.014155 2016] [:error] [pid 13825:tid 139644394280704] Traceback (most recent call last):
[Wed Apr 27 04:33:05.014166 2016] [:error] [pid 13825:tid 139644394280704]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
[Wed Apr 27 04:33:05.014174 2016] [:error] [pid 13825:tid 139644394280704]     rv = self.dispatch_request()
[Wed Apr 27 04:33:05.014180 2016] [:error] [pid 13825:tid 139644394280704]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
[Wed Apr 27 04:33:05.014187 2016] [:error] [pid 13825:tid 139644394280704]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Apr 27 04:33:05.014194 2016] [:error] [pid 13825:tid 139644394280704]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160422-py2.7.egg/ga4gh/frontend.py", line 550, in searchDatasets
[Wed Apr 27 04:33:05.014201 2016] [:error] [pid 13825:tid 139644394280704]     flask.request, app.backend.runSearchDatasets)
[Wed Apr 27 04:33:05.014207 2016] [:error] [pid 13825:tid 139644394280704]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160422-py2.7.egg/ga4gh/frontend.py", line 432, in handleFlaskPostRequest
[Wed Apr 27 04:33:05.014214 2016] [:error] [pid 13825:tid 139644394280704]     return handleHttpPost(flaskRequest, endpoint)
[Wed Apr 27 04:33:05.014223 2016] [:error] [pid 13825:tid 139644394280704]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160422-py2.7.egg/ga4gh/frontend.py", line 309, in handleHttpPost
[Wed Apr 27 04:33:05.014230 2016] [:error] [pid 13825:tid 139644394280704]     responseStr = endpoint(request.get_data())
[Wed Apr 27 04:33:05.014236 2016] [:error] [pid 13825:tid 139644394280704]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160422-py2.7.egg/ga4gh/backend.py", line 932, in runSearchDatasets
[Wed Apr 27 04:33:05.014243 2016] [:error] [pid 13825:tid 139644394280704]     self.datasetsGenerator)
[Wed Apr 27 04:33:05.014249 2016] [:error] [pid 13825:tid 139644394280704]   File "/srv/ga4gh/server/newserverenv/lib/python2.7/site-packages/ga4gh-0.2.3.dev12+ng19af245.d20160422-py2.7.egg/ga4gh/backend.py", line 685, in runSearchRequest
[Wed Apr 27 04:33:05.014255 2016] [:error] [pid 13825:tid 139644394280704]     raise exceptions.InvalidJsonException(requestStr)
[Wed Apr 27 04:33:05.014261 2016] [:error] [pid 13825:tid 139644394280704] InvalidJsonException: Cannot parse JSON: '{
[Wed Apr 27 04:33:05.014281 2016] [:error] [pid 13825:tid 139644394280704]   "pageSize": 10,
[Wed Apr 27 04:33:05.014288 2016] [:error] [pid 13825:tid 139644394280704] }'
```

**Comment by jeromekelleher** [comment]
Great, we're all happy with this then. I think we'll need to look at what Apache prints out now once this is in @david4096, and see what we need to do logging-wise. Let's try and get a list of requirements that we have under the [Logging milestone](https://github.com/ga4gh/server/milestones/Logging).

**Pull request merged**
