### PR TITLE
Added more config vars to html page

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #435

### CODE REVIEW

**Comment by jeromekelleher** [comment]
+1

**Comment by dcolligan** [comment]
@wstidolph would you like me to add any more vars to this PR?

**Comment by wstidolph** [comment]
MAX_RESPONSE_LENGTH and DEFAULT_PAGE_SIZE seem like the useful
configuration elements to add.

On Wed, Jun 3, 2015 at 8:24 AM, Danny Colligan <notifications@github.com>
wrote:

> @wstidolph <https://github.com/wstidolph> would you like me to add any
> more vars to this PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ga4gh/server/pull/439#issuecomment-108481865>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by dcolligan** [comment]
merge me!

**Pull request merged**
