### PR TITLE
Reorganization of new genotype handling code

### PR DESCRIPTION
**Pull request by mbaudrey**

### CODE REVIEW

**Comment by dcolligan** [comment]
You're going to need to squash your changes down to one commit before we are going to be able to accept this into master

**Comment by mbaudrey** [comment]
Commits have been squashed

**Comment by jeromekelleher** [comment]
+1, thanks @mbaudrey!

**Comment by kerrydc** [comment]
-1, I think this is better covered as I have done in my tabix fixes PR
(moves code in the Table superclass).

**Comment by interfect** [comment]
@kerrydc I'm looking for that PR and I can't find it; can you give the number?

**Comment by jeromekelleher** [comment]
I tend to disagree here @kerrydc --- these functions are logically standalone and do a single well defined task. I don't think they should be attached to any class, even a superclass. Also, the test case refactoring here is quite useful. Can you give a link to your PR though - I might change my mind!

**Comment by jeromekelleher** [comment]
Any further thoughts here @kerrydc? We can keep the functions as class methods if you prefer, but I would really like to see these changes to the tests go through.

**Comment by pashields** [comment]
I will +1 this. I think that #122 has useful additions on top of this, but since that may not be merged in the near-term, let's move forward with this.

**Comment by Naburimannu** [comment]
-0; there's no description of the justification for the change, and the commit message looks like an accidental cut-and-paste of one of mine?

**Comment by pashields** [comment]
Fair point @Naburimannu, the commit history here is a bit confusing.

**Comment by jeromekelleher** [comment]
Yes, good spot @Naburimannu. Can you edit the commit history please @mbaudrey? It is confusing, so we'll need to fix that before we can merge.

**Comment by mbaudrey** [comment]
Yes, I changed it. Sorry about that. I'm new to github

**Comment by dcolligan** [comment]
Is modifying the .travis.yml file and the requirements.txt file necessary?  That looks like a mistake...

It might be necessary to rebase your commit on top of the latest master to get the changes you need so that your commit only carries the necessary changes.

**Comment by mbaudrey** [comment]
HI all, I rebased and now there is a reasonable commit message and only my changes are showing. If everyone could take another look and +1 if you think everything looks good, it would be helpful.

**Comment by jeromekelleher** [comment]
+1. Thanks @mbaudrey!

**Comment by dcolligan** [comment]
+1

**Pull request merged**
