### PR TITLE
refactor BioSample and bio_sample to be Biosample and biosample 

### PR DESCRIPTION
**Pull request by kozbo**
for consistency. Fixes issue #1394

### CODE REVIEW

**Comment by dcolligan** [comment]
looks like there are some places that were missed:
```
$ ack bio_sample
docs/api.rst
38:        get_bio_sample, get_individual,
41:        search_reads, search_bio_samples, search_individuals

ga4gh/cli/client.py
252:        iterator = self._client.search_bio_samples(
276:        iterator = self._client.search_bio_samples(

ga4gh/client.py
103:    def get_bio_sample(self, biosample_id):
553:    def search_bio_samples(self, dataset_id, name=None, individual_id=None):

tests/end_to_end/test_client_json.py
190:            for biosample in self._client.search_bio_samples(dataset.id):
277:            iterator = self._client.search_bio_samples(dataset.id)
280:            for biosample in self._client.search_bio_samples(dataset.id):
281:                iterator = self._client.search_bio_samples(
290:                    iterator = self._client.search_bio_samples(

tests/unit/test_client.py
263:        self.httpClient.search_bio_samples(
325:        self.httpClient.get_bio_sample(self.objectId)

tests/unit/test_data_interface.py
72:            self._repo.allBiosamples, self._client.get_bio_sample)
227:            self._client.search_bio_samples,
```

**Comment by kozbo** [comment]
Thanks for catching those. PR updated

**Comment by dcolligan** [comment]
+1 after squash and rebase

**Comment by david4096** [comment]
I took a stab at updating this. I think that until the schemas are installable from their own repo working with new schema definitions is a bit obstreperous. Instead of running process schemas and updating the ga4gh-schemas repo, I will be able to `pip install git+ssh://git@github.com/david4096/schemas.git@684_desnake`.

**Comment by kozbo** [comment]
Closing this PR in favor of another PR that is more up to date, coming soon!

**Pull request closed without merging**
