### PR TITLE
File reorganisation

### PR DESCRIPTION
**Pull request by jeromekelleher**
This PR reorganises the files in the `ga4gh` package into a more logical order and opens the way for adding support for reads and references. Apologies for basing the diff on #59 - this was already quite a large change, so I thought it simpler to go with this route.  Hopefully that will be merged soon and we'll be able to see the changes here more clearly.

The basic gist of this PR is that we layout the code as follows:
```
ga4gh/
     __init__.py
     backend.py
     frontend.py
     protocol.py
     datamodel/
           __init__.py
          variants.py
          reads.py
          references.py
```
(I've left out a few files here that haven't been  affected.).

The idea is that we pull the classes in `backends.py` that are dealing with the GA4GH 'data model' and put them into their own package. We further split this package up into `variants.py`, `reads.py`, and `references.py`. I think it's a good idea to split these up as they are logically distinct and now that there's a lot of us working on the code, it'll be good to avoid merge issues.

I've renamed `backends` to `backend` since there is now a single `Backend` object. Similarly, I've renamed the server package to `frontend`, since it contains the Flask frontend. 

I changed the Flask frontend to use a single file for now. I did argue for separating it out into `views.py` and `__init__.py` when we were making the transition to Flask, but I don't think we're getting a lot of value out of this at the moment. We can always split things out again later if `frontend.py` is getting too complicated. 

I've made the minimal changes to the test cases to make them work. I think we should refactor and reorganise these as a separate PR later.

This is just a proposal to start a discussion, so please weigh in if you disagree with this layout!

### CODE REVIEW

**Comment by bioinformed** [comment]
Can I please get 2 hours of stability to add a new backend?  Please?  This rate of churn is making it unnecessarily hard for an "outsider" to contribute.

**Comment by jeromekelleher** [comment]
Sorry @bioinformed, we're trying to push through all these changes so that the code will be stable for the next few months, and we can all make progress without stepping over each other. If you work off the existing master and avoid changing too much I think git will figure out how to merge it back in easily enough. If not, everything you do can just be put into `datamodel/variants.py` when you're done.

I would just work ahead with what you're doing, and ignore these changes for now.

**Comment by kerrydc** [comment]
I'll review outstanding PRs tonight, so let's freeze development on
backends after Jerome's two PRs get in. Kevin, I've got a PR for the Tabix
backend that I am likewise waiting on, so I'll put that in after you.
Kerry

**Comment by bioinformed** [comment]
Many thanks. Please don't misunderstand: I like the unified paging PR and the other reorganizations. However, they do make working on the master branch less attractive. More so, because git can't carry forward the changes in a merge, because I'm adding an entirely new backend. Thus it would be really nice for the unified paging PR to land and for there to be a small window of stability.

**Comment by jeromekelleher** [comment]
This PR shouldn't affect what you're doing much @bioinformed, it's just moving stuff around in files. You can safely ignore it. #59 is different, as it changes the VariantSet API and should make it much, much simpler to work with. I would recommend setting up a upstream for my server repo (https://github.com/jeromekelleher/server) and rebasing your branch off my paging-cleanup branch. This should give you a stable platform to work with. I won't do any more rebasing, so you should then be able to merge your work easily.

To define the backend, just do a copy paste on the existing `TabixVariantSet`; yours should be very similar. We can figure out a good way to merge the two later.

Thanks for working on this htslib interface, and sorry again for all the churn!

**Comment by bioinformed** [comment]
Thanks! Working from your branch will work fine, since you're not going to rebase.

**Comment by kerrydc** [comment]
+1

**Comment by hershman** [comment]
+1

**Comment by kerrydc** [comment]
Jerome, if you could clean this up now that #59 is merged, I'll merge it today.

**Comment by jeromekelleher** [comment]
OK, this should be ready to merge. Please make sure to delete the .pyc files and server directory in your ga4gh directory, or weird things might happen.

**Comment by jeromekelleher** [comment]
This has been a bit of a mess to merge - hopefully should be sorted out now.

**Pull request merged**
