### PR TITLE
Add requirements.txt file

### PR DESCRIPTION
**Pull request by dcolligan**
Added requirements file

Issue #100

### CODE REVIEW

**Comment by dcolligan** [comment]
Okay, now this PR has a real requirements.txt candidate @jeromekelleher @Naburimannu

**Comment by Naburimannu** [comment]
+1

One of the next things I intend to work on will add heapy to the list of requirements. Do I just choose an arbitrary recent version #?

**Comment by dcolligan** [comment]
@Naburimannu Yeah, I guess.  Just install on your machine, verify it works, and then go with that.  Absent any more detailed requirements, that sounds like it should do the trick.

**Comment by jeromekelleher** [comment]
+1, thanks @dcolligan!

**Pull request merged**
