### PR TITLE
Rename pypi package

### LINKED ISSUE #1469: Update package name to ga4gh-server
When installing via pip we can use `ga4gh-server` to make the separation of concerns more clear.

### PR DESCRIPTION
**Pull request by david4096**
This can be done right before the next release and doesn't need interfere with current development. @dcolligan @kozbo 

* Logs a big ugly warning at server configuration time to use the new pypi package: `ga4gh-server`.

```
The pypi `ga4gh` module is being replaced with `ga4gh-server`. To continue to receive updates, please update your `requirements.txt`.
```

* Change setup.py to new pypi package name.

Next release, we make two releases with the "name" changed in the setup.py, adding or removing this warning as needed.

Breaks a test in test gestalt due to a logging error.

close #1469

### CODE REVIEW

**Comment by dcolligan** [comment]
I'm in favor of the package name change, but is anyone going to see that warning (except if they are developing)?

**Comment by dcolligan** [comment]
Ok, +1

**Comment by kozbo** [comment]
@dcolligan please go ahead with this for so we can include this change in the next release (hopefully next week).

**Comment by dcolligan** [comment]
Closing in favor of #1582

**Pull request closed without merging**
