### PR TITLE
Bring server up to date with linear schemas

### PR DESCRIPTION
**Pull request by dcolligan**
Bring server up to date with linear schemas

(submitting now to get the CI)

Issue #369

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This is great, thanks @dcolligan. How long do you think it'll take to make this mergable? I think we should get a straightforward version in ASAP (skipping more tests, if need be) and add some specific issues for the remaining stuff.

**Comment by dcolligan** [comment]
Not sure... digging into this presently...

**Comment by dcolligan** [comment]
So, good news: I've managed to fix all the tests but the end_to_end ones in my latest update.  Additionally, I've reenabled the tests in `test_schemas` and `test_avrotools` that we had commented out because of the borked schema, and they work.  The server seems to be functional now; I just need to adjust the client (especially the cli) to correspond with the new search request objects.

**Comment by dcolligan** [comment]
@jeromekelleher ok, tests should be passing... ready for review

**Comment by jeromekelleher** [comment]
Fast work @dcolligan! This looks good to me, let's merge!

+1

**Comment by dcolligan** [comment]
Great.

**Pull request merged**
