### PR TITLE
Test for server startup

### PR DESCRIPTION
**Pull request by dcolligan**
(Also change a public method to not be named as a private method.)

Issue #898

### CODE REVIEW

**Comment by jeromekelleher** [comment]
+1.

**Comment by dcolligan** [comment]
rebased and ready to merge

**Comment by jeromekelleher** [comment]
Oops, merged the other PR first. Github insists on a rebase.

**Comment by dcolligan** [comment]
@jeromekelleher rebased

**Comment by jeromekelleher** [comment]
Gah, merged the other PR first again! These protected branches are a bit tedious sometimes.

**Comment by dcolligan** [comment]
Oh, so protected branches solve github's broken merge model?  Yay!  No more failed tests in trunk branches!

**Comment by dcolligan** [comment]
@jeromekelleher updated

**Comment by dcolligan** [comment]
I merged it

**Comment by jeromekelleher** [comment]
Ta.

**Pull request merged**
