### PR TITLE
test to validate mimetypes config, a dependency of oidc-provider

### PR DESCRIPTION
**Pull request by bwalsh**
Purpose of this PR is an initial validation of the github workflow as well as a simple test of oidc-provider mimetypes dependency.

```
-----------------------------------------------------------
TOTAL                          3928    352    91%
----------------------------------------------------------------------
Ran 290 tests in 67.713s
```

### CODE REVIEW

**Comment by dcolligan** [comment]
Looks great, but I'm sure this is going to fail CI because of style violations.  Use `scripts/run_tests.py` to run the CI locally (including flake, which checks style).

**Comment by bwalsh** [comment]
` because of style violations.`  perfect, I hoped the PR would smoke out issues like that. Fixed.

**Comment by dcolligan** [comment]
Awesome.  I'm ready to +1 this after the commits are squashed.  See http://ga4gh-reference-implementation.readthedocs.org/en/develop/development.html#github-workflow

**Comment by bwalsh** [comment]
Thanks.  Looks like commits squashed ok.

**Comment by dcolligan** [comment]
+1

**Comment by jeromekelleher** [comment]
This is a great test, thanks @bwalsh. There seems to be some issue with the PR though, as the commit for the g2p stuff has come in here as well. Also, this PR is against the g2p branch, and something like this should be against the develop branch so we can use it immediately.

**Comment by dcolligan** [comment]
agree with jerome -- strip out the test and file it against `develop` in its own PR and we'll be able to merge it

**Comment by bwalsh** [comment]
Thanks guys.  Letting the g2p stuff slip in was an oversight.

-b

-Brian Walsh

**Pull request closed without merging**
