### PR TITLE
Issue 523

### PR DESCRIPTION
**Pull request by pcingola**
Added test case

Added tests in test_cli.py and test_client.py

Added testCors in test_views.py

Added testCors in test_views.py

Added testGetDataset in test_simulated_stack.py

Adding 404 check to testGetDataset

Removing comment

### CODE REVIEW

**Comment by jeromekelleher** [comment]
How did @dcolligan become the author of this commit? This is weird! 

@dcolligan (as the resident git expert), can you take a look at this and see what needs to be done to make it look like it should? Posting the exact commands would be helpful.

I accept git is confusing initially @pcingola, but it really is so much more powerful once you get the hang of it. We need to update the docs with a simpler method of rebasing and squashing I think.

**Comment by pcingola** [comment]
I've used many versioning systems in my life. 
No, it doesn't need to be this complicated. 
It's just broken.

**Comment by dcolligan** [comment]
Looks like the newest changes from develop got put into this commit somehow.  Not sure how this happened (in general, it's hard to tell exactly what went wrong with screwed up branch X).

These commands will fix this:
```
# make sure your local develop branch is up to date
$ git fetch --all
$ git checkout develop
$ git merge --ff-only upstream/develop
# create a new branch; name it whatever you'd like
$ git checkout -b new_branch
# cherry pick your commit onto this new branch; since the changes you don't want to incorporate are already in the develop branch, this should only put the diff (that is, your desired changes) in the commit
$ git cherry-pick b27fea38f84f8e5b91c7fbf9585aadb31e47ae94
# give yourself authorship
$ git commit --amend --reset-author
# force push your new local branch to the same remote branch that is now screwed up, effectively overwriting it with the correct changes
$ git push -f origin new_branch:get_dataset_by_id_squashed_squashed
```

I recommend reading up a bit on git since it is what we use (not to mention probably the most-used RCS for new projects these days): https://git-scm.com/book/en/v2

**Comment by diekhans** [comment]
Hi Pablo,

git a brilliant idea (although not unique) implemented in a
bizarre and confusing way.  It is amazing powerful.  The
documentation is a huge part of the problem.  The basic
documentation is not that good, especially on how to actually
apply it and why features are there.  The community advice you
get is conflicting, such as never rebase vs almost always
rebase.

It's the most complicated development tool I have ever seen.

The best thing to do is ask.  Danny is especially good at it.
The SourceTree application is really useful as well.

Mark

**Comment by pcingola** [comment]
This PR is one commit as required. Can we just merge it?

**Comment by dcolligan** [comment]
No, we're not going to merge in changes to a mainline branch that aren't the right ones.  At this point you can either:
1) follow the steps I outlined above
2) rebase your branch on top of develop, which will likely do the same thing, and resubmit it
3) have me submit a new PR with your changes and merge that, if you want me to take your changes from here

**Comment by pcingola** [comment]
Sure, go ahead with option 3.

**Comment by jeromekelleher** [comment]
I'm sorry this has been so frustrating @pcingola. 99% of the time, all squashing entails is
```
$ git checkout topic-branch
$ git fetch upstream
$ git rebase -i upstream/develop
$ git push -f origin topic-branch
```
Squashing tends to go horribly wrong the first few times you do it, but completely smoothly after that when you get used to keeping your topic branches current and avoiding conflicts. I don't think we're being unreasonable in wanting to keep our history clean. This is really, really useful when it comes to maintaining many branches and releases, and it's fairly standard practise in git projects involving more than one developer. 

Anyway, thanks for adding this functionality and I hope you're not put off from contributing more by the git requirements. We do need to improve the documentation for this, as it is the single biggest obstacle for new developers wanting to contribute.

**Pull request closed without merging**
