### PR TITLE
Changed FASTA library to pyfaidx...

### PR DESCRIPTION
**Pull request by macieksmuga**
...and introduced an optional parameter on `SearchSequenceRequest`  that causes a  string to be given for every base returned.

### CODE REVIEW

**Comment by macieksmuga** [comment]
and changed it back once it became clear that pyfaidx was causing more problems than it was solving. Sigh.

**Comment by bioinformed** [comment]
What was the problem?  Also, have you tried the native index FASTA support
in pysam?

**Comment by macieksmuga** [comment]
I believe the issue was with the string conversion: Pyfaidx returns bases in a custom type, that I then had to convert explicitly to string (so that it could be embedded into the JSON output stream). I saw no facilities to enable pyfaidx to emit the bases as a string to begin with.

I had initially experimented with alternate FASTA libraries due to poor performance of the graph server, but have since found two unrelated bugs that accounted for most of the problem. Thus I reverted to the library I had been using previously.

Independently of the above, I'd be happy to explore FASTA support in pysam, so long as it delivers similar or better performance to the current benchmark.

**Comment by bioinformed** [comment]
The pysam Fastafile object is a pretty basic wrapper around the htslib
code.  See http://pysam.readthedocs.org/en/latest/api.html#pysam.FastaFile.

**Comment by mdshw5** [comment]
I'm probably way too late on this but pyfaidx supports the `as_raw` argument which will just return a Python string. Depending on your usage, this will be much faster than either samtools or pysam, without depending on a C compiler.

**Pull request merged**
