### PR TITLE
remove feature_id from ExpressionLevel

### PR DESCRIPTION
**Pull request by saupchurch**
remove feature_id from ExpressionLevel and changes search to filter by name
depends on:
https://github.com/ga4gh/schemas/issues/829

### CODE REVIEW

**Comment by ejacox** [comment]
+1

**Comment by david4096** [comment]
@saupchurch thanks for taking a look at this! Once the tests are updated I think it will be ready to merge!

**Comment by saupchurch** [comment]
@david4096 thanks.  I should have updated test shortly.

**Comment by kozbo** [comment]
closes #1580

**Comment by ejacox** [comment]
I removed an unused parameter that was causing one test to fail. The tests pass. However, the constraints file pointing to the correct schemas and client wasn't checked in, so travis is failing here.

**Pull request merged**
