### PR TITLE
Unique ids for top-level objects

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #1012 

(Alternative to #1022)

### CODE REVIEW

**Comment by dcolligan** [comment]
Could I get a review on this?  It's part of the 1000g milestone @jeromekelleher

**Comment by diekhans** [comment]
looks very sane to me

**Comment by macieksmuga** [comment]
While the this fix addresses the issue of the moment, I'd like us to have a longer-view architectural discussion about the role and implementation of the ID scheme.
To this end I created a google doc, that will hopefully serve as a focus of such discussions:

https://docs.google.com/a/soe.ucsc.edu/document/d/1xhzM3_jGL0OgpEElok-5WGsdlfUxQ6KjF78jaFOdIvw/edit?usp=sharing

**Comment by david4096** [comment]
Seems to work, thanks for clearing things up +1!

**Comment by jeromekelleher** [comment]
OK, thanks @dcolligan. +1, merging.

**Pull request merged**
