### PR TITLE
Throw exception if DB does not exist

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #1141

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good. Some stuff we need:

1. Test cases in the CLI. Verify that the correct exception (RepoNotFoundException?) is thrown when we pass a bad argument to the various commands.
2. Should we check the DB schema here as well? We should try to load (a) some text file, and throw a BadRepoFormatException(),  (b) an empty SQLite DB, (c) a directory. We want to make sure that a sensible error message is sent back to the user for every possible class of stupid input here.

**Comment by dcolligan** [comment]
@jeromekelleher updated

**Comment by jeromekelleher** [comment]
Awesome, +1.

**Comment by jeromekelleher** [comment]
Can you rebase and merge please @dcolligan?

**Pull request merged**
