### PR TITLE
Increase line length

### PR DESCRIPTION
**Pull request by david4096**
Was defaulted to 80, increases to 100 with this change. @dcolligan

### CODE REVIEW

**Comment by dcolligan** [comment]
Wait, why?

-1

**Comment by david4096** [comment]
Any other opinions? I find 80 unnaturally restrictive on these widescreen monitors. 💯 

http://i.stack.imgur.com/XvPKy.jpg

**Comment by dcolligan** [comment]
Yes, but many of us use standard-width terminals in monitors, widescreen or not

**Pull request closed without merging**
