### PR TITLE
s/properPlacement/improperPlacement/

### PR DESCRIPTION
**Pull request by dcolligan**
A version of @calbach 's #959 without the erroneous diffs in _protocol_definitions.py

### CODE REVIEW

**Comment by dcolligan** [comment]
@david4096 can you review and merge?

**Comment by david4096** [comment]
Should the schema version be a2 or 3? Looks fine but if this is part of the server's release we ought to match the schema version number.

**Comment by diekhans** [comment]
We already release a2, so this is a3

**Comment by dcolligan** [comment]
updated with a3

**Comment by david4096** [comment]
+1

**Comment by dcolligan** [comment]
Thanks, @calbach !

**Pull request merged**
