### PR TITLE
fix command for script

### LINKED ISSUE #1329: Development docs out of date regarding protocol buffers
The development documentation is out of date about using `process_schemas.py`, etc. with regard to protocol buffers.

### LINKED ISSUE #1392: Create release for G2P, v0.3.4
create release notes for the server

### PR DESCRIPTION
**Pull request by kozbo**
Fixes #1329, supersedes PR #1396

### CODE REVIEW

**Comment by dcolligan** [comment]
+1

**Comment by dcolligan** [comment]
Although I will note that this doesn't satisfy #1329 ... the protobuf python lib is listed in `requirements.txt`, but `process_schemas.py` uses the protobuf compiler, which is a command line utility installed separately

**Comment by kozbo** [comment]
@dcolligan ah, ok. should I add the protobuf compiler requirement to the dev_requirements.txt file then?

**Comment by dcolligan** [comment]
No, since it's not a python package

**Comment by dcolligan** [comment]
(unless you can find a python package that installs `protoc`, but I doubt there is one)

**Comment by kozbo** [comment]
@dcolligan ok, added section on installing protocol buffers.

**Pull request merged**
