### PR TITLE
A script for counting lines of code in the repo

### PR DESCRIPTION
**Pull request by dcolligan**
Some fun stats:
```
 274 files changed, 32815 insertions(+), 4 deletions(-)

     183 text files.
     171 unique files.
     172 files ignored.

http://cloc.sourceforge.net v 1.60  T=0.30 s (335.2 files/s, 87145.8 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Python                           94           3430           6349          16028
make                              1             31              6            157
HTML                              1              2              0            122
YAML                              2              7             14             69
Bourne Again Shell                1              5              6              9
Bourne Shell                      2              5              9              9
--------------------------------------------------------------------------------
SUM:                            101           3480           6384          16394
-------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by dcolligan** [comment]
@david4096 can you review this?

**Comment by david4096** [comment]
Hm, says I don't have `cloc`.  
```
274 files changed, 32815 insertions(+), 4 deletions(-)
scripts/count_loc.sh: line 15: cloc: command not found
```

**Comment by dcolligan** [comment]
Well yeah you need to have that binary installed on your system.  Whatever package manager you use should have it.

**Comment by david4096** [comment]
I'm -1 to add a script to count lines of code.

**Comment by diekhans** [comment]
This seems very, very low priority.  Lines of code is not a good
complexity metric.  While running better metrics is useful, it
seems low-priority to make it a requirement even for developers

**Pull request closed without merging**
