### PR TITLE
Fix master by excluding conf.py from flake8 check

### PR DESCRIPTION
**Pull request by dcolligan**
(Lol @ GitHub's broken merge model)

### CODE REVIEW

**Comment by dcolligan** [comment]
making an executive decision and merging to fix master

**Comment by shajoezhu** [comment]
+1

**Comment by jeromekelleher** [comment]
Good call on the executive decision @dcolligan. I'm confused about what got broken though: what is conf.py?

**Comment by shajoezhu** [comment]
This was likely caused merging my branches into the master. I added "docs/source/conf.py" on branch "reduce_readme"PR#318. but I also modified .travis.yml, to check the coding style at the root level, this was on branch "checking_coding_style" PR#314.

**Comment by jeromekelleher** [comment]
Ah I see --- this is still using the recursive check on all subdirs. We should get @dcolligan's PR merged ASAP to turn this off.

**Pull request merged**
