### PR TITLE
Support multiple test buckets

### PR DESCRIPTION
**Pull request by dcolligan**
Add a unit, integration and an end_to_end test bucket.  All existing tests are put in the unit test bucket.

Currently, Travis and `run_tests.py` will still run all tests by default, regardless of what bucket they are in.  When someone adds a test that they do not want run by Travis because of its expensiveness, perhaps we can revisit this policy.

Issue #106

### CODE REVIEW

**Comment by dcolligan** [comment]
To see where each file moved, you need to click the "Showing  12 changed files  with 15 additions and 19 deletions." link under the files changed tab.

**Comment by Naburimannu** [comment]
+1

**Comment by jeromekelleher** [comment]
+1

**Comment by jeromekelleher** [comment]
Github won't let me merge this - rebase maybe @dcolligan?

**Comment by dcolligan** [comment]
Just rebased... you can merge after the CI passes

**Comment by dcolligan** [comment]
It passed... ready to merge!

**Pull request merged**
