### PR TITLE
Add run_tests.py to imitate travis run

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #96

### CODE REVIEW

**Comment by dcolligan** [comment]
cc'ing everyone who was chatting in #95 

@pashields @jeromekelleher @Naburimannu

**Comment by jeromekelleher** [comment]
This is pretty neat! So, the idea is that we can run this script before pushing to save the trouble of running the travis build? Seems like a useful tool to me.

Do we need the extra `dev_scripts` dir? It seems to me that they're all dev scripts really - this one and `generate_schemas.py` don't need to be in the root as they don't import  `ga4gh`. Maybe move this one into `scripts/`? Or rename `scripts/` to `dev_scripts` if you prefer?

**Comment by dcolligan** [comment]
@jeromekelleher The idea is Travis will likely not run on the commit we want it to, when we want it to.  When one pushes a PR, Travis will do a merge into master and then run CI on that.  That CI result is different than the one that we really want, which is the merge into master *at the time that the merge is going to take place.*  That is, master may have changed between when Travis runs CI and when we want to run CI.  This is why we couldn't catch the test breakage before.

I'm not sure if re-submitting a Travis job will merge onto the current master, or the master that it previously ran on.  If it's the second, then we definitely need my change, and should incorporate it into our merging flow.  If it's the first, then the importance of my change reduces to 1) a convenient way for devs to see if travis will reject their change before submitting the PR 2) a faster way to get travis results than through travis itself.  In either case, I think it's warranted.

**Comment by jeromekelleher** [comment]
>I'm not sure if re-submitting a Travis job will merge onto the current master, or the master that it previously ran on. If it's the second, then we definitely need my change, and should incorporate it into our merging flow. If it's the first, then the importance of my change reduces to 1) a convenient way for devs to see if travis will reject their change before submitting the PR 2) a faster way to get travis results than through travis itself. In either case, I think it's warranted.

I think it's (1), as the documentation that @pashields shows. I've kicked off a bunch of previously failing PRs, which are fine now, so I think this is fairly conclusive. I still like this PR though, it's a useful tool. It's tedious having to remember to check coverage and pep8 each time, and travis builds takes ages, so this is a neat shortcut.

**Comment by pashields** [comment]
I'm good with this change, but it does not replace a travis run, particularly when we start to talk about supporting more than one version of python. But travis also provides a clean repeatable env. "run_tests.py worked on my box" is not a valid excuse.

In the long run, we may wish to actually parse the travis yaml file rather than manually sync these. If this is a real blocker for work right now, I'm fine to have a TODO in there.

Also, to be clear, I'd view it as the responsibility of the person running the merge to re-run travis.

**Comment by dcolligan** [comment]
Ok, submitted a change where I'm now parsing the yaml, but I needed to move some things around in the `.travis.yml` file.  It would seem to make sense to me to keep everything that we want to run as an actual test (vs setup) under the `script:` entry.

**Comment by pashields** [comment]
awesome. Assuming tests pass, I can happily +1 this.

**Comment by Naburimannu** [comment]
+1

**Comment by jeromekelleher** [comment]
This really is very nice! One thing: is yaml a third party lib? If so, I think there should be a blank line between the imports.

I'm not suggesting we do it here, but I think we should try to keep track of all the third party libs we're using for testing and dev. It'd be nice to be able to install all these from a `requirements.txt` or whatever when testing in a virtualenv.

**Comment by dcolligan** [comment]
@jeromekelleher pushed a change with the extra newline you requested

File an issue for a requirements.txt, that sounds like a good idea

**Pull request merged**
