### PR TITLE
Add deobfuscated ids to html page

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #585

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Why are we deobfuscating the IDs rather than just using (e.g) ``dataset.getName()``? The name is the human readable identifier, and the hierarchy should be clear from the display, so I don't see why the user needs to know what's inside our IDs (and, I think there's a clear opportunity for them to get confused by this). Perhaps we should have an explicit table with headers and borders, with **name** and **id** for each object?

**Comment by dcolligan** [comment]
There is no `getName` method.  Are you suggesting adding one (perhaps on DatamodelObject) that returns the deobfuscated id?

**Comment by jeromekelleher** [comment]
Sorry, that should have been ``getLocalId()`` --- this is what we're mapping to the ``name`` concept at the moment.

**Comment by dcolligan** [comment]
@jeromekelleher updated

**Comment by jeromekelleher** [comment]
This looks soooo much better! I really like this @dcolligan, thanks. It's easy to see how we can build this page into a really useful summary of the data from here.

There's one potentially sticky issue though: licensing-wise, are we OK shoving in the jquery source? It looks like jquery is MIT licensed, so I think we're OK. I'm no license lawyer though, so it would be nice to get some other opinions on this.

**Comment by dcolligan** [comment]
Yeah, I'm not sure either.  One option is to source the js / css from CDNs but that can be annoying if developing locally, so I'd rather not do that.

**Comment by jeromekelleher** [comment]
Any ideas who we should ask about licencing related issues? Anyone?

**Comment by dcolligan** [comment]
Just to record this, it was resolved on the call that we should fetch the libs from a CDN rather than check them into our source code tree.

**Comment by dcolligan** [comment]
@jeromekelleher js/css now loaded from CDN

**Comment by jeromekelleher** [comment]
Thanks @dcolligan --- merging.

**Pull request merged**
