### PR TITLE
Reverted to v0.5 semantics for variants-search.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Reinstate full v0.5.1 semantics for variants-search.

### CODE REVIEW

**Comment by dcolligan** [comment]
Er, what is this PR about?

**Comment by jeromekelleher** [comment]
Well, we've got an unfortunate situation at the moment in that the semantics for the search variants request is actually backported from the 0.6 schema. (This was before we started working with a well-defined schema from a release.) This PR reinstates the (really horrible) semantics that we need for 0.5 compliance.

**Comment by diekhans** [comment]
Branch 0.5 an fix in a sane wsy???



... Sent from my computer phone

-----Original Message-----

**Comment by dcolligan** [comment]
Well, if we're locked in, we're locked in.

Keeping this in one commit will be convenient since we can do a git revert [this commitish] in the 0.6 branch to roll back the changes.

+1

**Comment by macieksmuga** [comment]
Ya gotta do what ya gotta do. Required changes are thankfully pretty minor :)
+1

**Pull request merged**
