### PR TITLE
Routine to set sam flags mistakenly assumes integer is passed by ref

### PR DESCRIPTION
**Pull request by mp15**
Make this routine return the value instead.

### CODE REVIEW

**Comment by dcolligan** [comment]
oh man, how did we miss that.  lol 

good catch

+1

**Comment by mp15** [comment]
just realised there's one more thing that needs changing line 175 is wrong

**Comment by dcolligan** [comment]
this fixes #748, I presume?

**Comment by jeromekelleher** [comment]
Great catch. I think it's pretty clear the test coverage is poor on this code!

+1.

**Comment by macieksmuga** [comment]
Added test case for header in `test_converters.py` also partly fixes #707

**Comment by dcolligan** [comment]
the CI is failing because of syntax errors

**Comment by mp15** [comment]
Fixed them.

**Comment by dcolligan** [comment]
+1

**Pull request merged**
