### PR TITLE
Add endpoint for finding variant annotation sets by ID

### LINKED ISSUE #827: Variant Annotation - GET  VariantAnnotationSet
GET /variantannotationsets/{id} endpoint needed

### PR DESCRIPTION
**Pull request by david4096**
Fixes #827, depends on #845

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Likewise here, rebase on ``upstream/variation_annotation``.

**Comment by david4096** [comment]
Alrighty then!

**Comment by jeromekelleher** [comment]
Looks good @david4096, this just needs to be rebased on upstream/variation_annotation once #845 is merged. You also need to fix some pep8 issues which are currently failing CI. 

For sanity's sake, I've found it useful to add a pre-commit hook to check for flake8 problems, .e.g, add
```bash
exec flake8 *.py tests ga4gh scripts --exclude=ez_setup.py
```
to .git/hooks/pre-commit

Also, you might want to add  auto dead-whitespace removal to your editor.

**Comment by jeromekelleher** [comment]
Rebase required here @david4096.

**Comment by jeromekelleher** [comment]
OK, something went wrong here. I think you need to rebase off the current state of upstream/variation_annotation on these PRs. Don't worry about pulling in commits from master, that gets done seperately.

**Comment by david4096** [comment]
updated @jeromekelleher

**Comment by jeromekelleher** [comment]
Perfect. For these 'feature branch' PRs we're using rebases rather than merges to keep the branch up to date, as this gives a more linear history. A quick rebase against upstream/variation_annotation and force push will sort it.

+1 after rebase.

**Comment by david4096** [comment]
Rebased! @jeromekelleher :)

**Comment by jeromekelleher** [comment]
Merging, thanks @david4096.

**Pull request merged**
