### PR TITLE
Added install requires for humanize package.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Fixes missing install requirement.

### CODE REVIEW

**Comment by dcolligan** [comment]
Can't you just change that line to read in and parse the `requirements.txt` file, so we don't have to keep updating them in parallel?

**Comment by pgrosu** [comment]
@dcolligan, I totally agree with this approach, but I could see an issue with automatizing the `wormtable` installation if it's not installed.

**Comment by dcolligan** [comment]
A problem that isn't present by hardcoding it in the `setup.py` file?

**Comment by pgrosu** [comment]
Good point :)

**Comment by jeromekelleher** [comment]
They are for different things @dcolligan --- setup.py contains only what we need to deploy, whereas requirements.txt contains everything we need to develop.

**Comment by dcolligan** [comment]
+1

**Pull request merged**
