### PR TITLE
Fixes redundant and slow flake8 run

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #319

### CODE REVIEW

**Comment by dcolligan** [comment]
It looks like travis uses the shell to run commands, so this will work (which I suppose could be inferred from how it presently behaves in regard to our existing config file).

**Comment by jeromekelleher** [comment]
+1.

**Comment by shajoezhu** [comment]
+1

**Comment by dcolligan** [comment]
@jeromekelleher merge me!

**Pull request merged**
