### PR TITLE
Update protobuf branch with latest changes from master

### PR DESCRIPTION
**Pull request by irene-lshift**
Same as https://github.com/ga4gh/server/pull/1242 but against your protobuf branch

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Great, thanks. Let's keep the discussion over at #1242, and then merge this PR into the protobuf branch once we're all happy with it.

**Comment by david4096** [comment]
+1 from me!

**Comment by jeromekelleher** [comment]
+1 to merge.

**Comment by macieksmuga** [comment]
+1

**Pull request merged**
