### PR TITLE
Changed links in README to point to develop branch.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Changes the links for the version of the README in develop to point to the docs in develop. I guess when we create a release branch for the 0.2 version we can change these back to stable, so that we're pointing at the right version from PyPI. This is slightly error prone though, so if anyone has better ideas please shout.

Discussion on #509.

### CODE REVIEW

**Comment by dcolligan** [comment]
Hm... tricky issue.  I guess if there is information like this that we want to remain different in certain branches it makes sense to have it somewhere else besides in the branche(s) proper since, as you point out, the state in a certain branch that we want to keep will get overwritten in a merge unless we are careful to manually specify it.  But if we want to keep the readme file as is, we're kind of stuck with that...

How about this as an alternative?  Link both the develop and stable branches in the README.  E.g.  "Here is the link for documentation about this line, here is the documentation for that line."  That is, the READMEs in both branches are the same, and we don't need to worry about not updating them as we go forward.

**Comment by jeromekelleher** [comment]
This is a tricky one all right. Your idea is more maintainable, but I worry about the potential confusion on the [PyPI page](https://pypi.python.org/pypi/ga4gh). This should be our first point of contact with the majority of users as we become more mature, and it would be good to have a simple message to follow there.

Perhaps this is being caused by our current trick of using the README.rst as the landing page for both GitHub and PyPI. Maybe we should have two separate ones? One is focused on users and the other on devs?

**Comment by dcolligan** [comment]
That's another idea.

Yet another idea would be to just send people to the readthedocs page, with no branch specified.  That will be applicable for all branches, if a bit ambiguous.

**Comment by jeromekelleher** [comment]
>Yet another idea would be to just send people to the readthedocs page, with no branch specified. That will be applicable for all branches, if a bit ambiguous.

I'm not crazy about this one --- it's not at all obvious what branch you're looking at when you hit readthedocs. I this would lead to even more confusion than we have now.

I'll make a new PR with a proposal for the two README's approach.  Putting a -1 on this one until we've decided which one we prefer.

-1.

**Comment by dcolligan** [comment]
The other PR seems better... closing...

**Pull request closed without merging**
