### PR TITLE
Removed check for Debug so that we always log exceptions.

### LINKED ISSUE #1099: logging exceptions should not be controlled by DEBUG and should default to enabled
It would be really good for server to use the syslog (also python logging) conceptual model.  In particular, logging uncaught exceptions would not be controlled by a option called DEBUG.  This is at least level
`Error'.  This should default to `on'.

see https://en.wikipedia.org/wiki/Syslog#Severity_level

Since logging exceptions is the only thing controlled by `DEBUG',  please change this to default to True until it can be made consistent with syslog.

### PR DESCRIPTION
**Pull request by kozbo**
some nosetests are still failing.

Will close #1099

### CODE REVIEW

**Comment by diekhans** [comment]
changing the default for DEBUG might be a better short-term approach.

**Comment by jeromekelleher** [comment]
I'm fine with this as a short-term workaround while we implement proper logging. Not sure why the tests are failing, looks pretty strange. If you like you can put in a check for testing (I'm sure the Flask server sets this somewhere in the config) to suppress the stack dump in this situation (again, as a workaround).

**Comment by kozbo** [comment]
Tests now pass. The earlier failures were due to the test code generating request exceptions without going through the request pathway, thus they were out of context.
... but 
It turns out that app.log_exception() doesn't generate any output if the flask debug flag is off. So my earlier change was insufficient. Added basic logging to stderr and now we see the output again.  There are some tradeoffs to this approach:

- Exceptions generated when running in the development mode will be printed to the console twice, once by flask and once by us. 
- The nose tests will generate a lot of exception output which will give you a scare until you realize that many of these are negative tests. All tests run OK in the end.

Someone might have an idea on how to avoid the first drawback above. If so I would love  to hear it :-)

**Comment by diekhans** [comment]
thoughts:

for #1, on this page, it looks like one is not suppose to mess with the logger
if debugging is enabled and set it if it is not:
   http://flask.pocoo.org/docs/0.10/errorhandling/
there maybe subtleties with debugging turned on and handling
exceptions.  Probably following this paradigm is good.

For #2, we could just setup a logger that sends the output to a
file instead of stderr, but I don't know how nose works so I
don't know any drawbacks.

**Comment by diekhans** [comment]
I looked at the flask code and debug mode adds it's own logger,
hence the prescription to only add a logger if debug is not
enable.

**Comment by jeromekelleher** [comment]
Hmm, this is tricky. Perhaps we could just duplicate the code that Flask uses to add the logger in DEBUG mode, without turning on DEBUG? However, the present workaround is fine if you want to get something in quickly --- we can worry about spamming the output of nosetests later.

**Comment by diekhans** [comment]
The flask documentation gives clear guidance on how setup logging
and app.debug 

    http://flask.pocoo.org/docs/0.10/errorhandling/

**Comment by jeromekelleher** [comment]
+1.

**Comment by dcolligan** [comment]
on the call we decided to merge this (before the release)... merging now...

**Pull request merged**
