### PR TITLE
Feature/feature 701 unused exceptions

### PR DESCRIPTION
**Pull request by denis-yuen**
This removes the two unused exceptions and adds a ~/.travis.yml step to automatically check for them in the future

See https://travis-ci.org/denis-yuen/server/builds/84943690 for proof that the tests pass

### CODE REVIEW

**Comment by dcolligan** [comment]
A number of things:

1) You don't need to post proof that the CI build passes... the Travis CI build will kick off when you submit a PR ... this should give the same result as `python scripts/run_tests.py`

2) For us to accept a PR, we usually like to have it in one commit, so these commits need to be squashed into one

3) When I run `vulture .` on the project I get this error: `RuntimeError: maximum recursion depth exceeded`

4) Anything that is in `.travis.yml` gets run every time on travis and also by `run_tests.py` so we only want to put in there what we want to run on every test run... I'm not sure if this qualifies as is.  Vulture seems like a useful tool (if it works) to run once in a while.

5) I would be up for accepting just the changes in `ga4gh/exceptions.py`.  If you resubmit the branch with those changes alone, I think that was more what the original issue was asking for.  (er, now that I look at the issue, it seems like the issue *was* asking for incorporating vulture into CI, but let's not do that for now)

6) We usually like the issue number in the commit message: `Issue #701` for this issue, for example.

**Comment by jeromekelleher** [comment]
Looks like vulture might be a bit tricky to incorporate without more evaluation. I think we should trim this PR back to just the changes to exceptions.py, just in case we introduce some problems for people. Thanks for the check though, hopefully we can integrate with something like this later!

**Comment by dcolligan** [comment]
+1

**Comment by jeromekelleher** [comment]
+1.

**Pull request merged**
