### PR TITLE
Update _protocol_definitions to schemas/4568e6f6

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #599

### CODE REVIEW

**Comment by jeromekelleher** [comment]
+1.

Shall we pull in the latest (and final) changes in here or do a separate PR?

**Comment by dcolligan** [comment]
Isn't 4568e6f6 the latest change?

**Comment by jeromekelleher** [comment]
No, I don't think so; I'll open another issue for this. Merging this PR.

**Comment by jeromekelleher** [comment]
Nope, my bad; looks like this is the head of the schemas.

**Pull request merged**
