### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by dcolligan**
- avrotools is now recursive

Issue #358
Issue #360
Issue #361

### CODE REVIEW

**Comment by macieksmuga** [comment]
Makes sense - we're creating increasingly deeper nested Avro definitions.
Thank you!
+1

**Comment by jeromekelleher** [comment]
Great work @dcolligan, thanks. 

+1.

**Comment by pgrosu** [comment]
+1 Just not too many levels @macieksmuga :)

**Comment by dcolligan** [comment]
@jeromekelleher merge me!

**Pull request merged**
