### PR TITLE
Delete unused routes

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #522

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks good. This does depend a little on the outcome of  #372 a bit, but lets assume that it'll be compatible with this PR. 

+1.

**Comment by dcolligan** [comment]
#372 ?  That issue is closed...

**Comment by jeromekelleher** [comment]
Sorry, that should have been ga4gh/schemas#372.

**Comment by dcolligan** [comment]
@jeromekelleher merge me!

**Pull request merged**
