### PR TITLE
Does this break?

### PR DESCRIPTION
**Pull request by dcolligan**
Testing Jerome's theory about CI failing because of non-pinned library

### CODE REVIEW

**Comment by dcolligan** [comment]
No, it does not break!

**Comment by dcolligan** [comment]
@jeromekelleher

**Comment by jeromekelleher** [comment]
Weird... Thanks for testing this out @dcolligan.

**Comment by dcolligan** [comment]
Oh, I know why this still works... your error only was caused when you ran the `ga4gh_server` installed package, and we don't do that anywhere in the CI.  We should add that somehow.

**Pull request closed without merging**
