### PR TITLE
Variation annotation

### PR DESCRIPTION
**Pull request by david4096**
This pull request adds POST endpoints for `variantannotations/search`, `variantannotationsets/search`, and a GET endpoint for `variantannotationsets/`.

If you have maven, virtualenv, and pip setup you can take it through its paces:
```
# Get the Compliance Suite and Test Data

git clone git@github.com:ga4gh/compliance.git
cd compliance
git checkout variation_annotation
mvn clean install
unzip dist/target/ga4gh-ctk-cli.zip

# Get the Reference Server and Add Compliance Test Data
cd ..
git clone git@github.com:ga4gh/server.git
cd server
git checkout variation_annotation
virtualenv serverenv
source serverenv/bin/activate
pip install -r requirements.txt
nosetests
python scripts/prepare_compliance_data.py -i ~/compliance/test-data -o ga4gh-example-data
python server_dev.py

# Should see something like
#  Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)

# Open a web browser to see the landing page
python client_dev.py variantannotations-search --variantAnnotationSetId YnJjYTE6T1I0Rjp2YXJpYW50YW5ub3RhdGlvbnM= --start 69500 --end 69530 --referenceName 1 http://localhost:8000

# And filter by term
python client_dev.py variantannotations-search --variantAnnotationSetId YnJjYTE6T1I0Rjp2YXJpYW50YW5ub3RhdGlvbnM= --start 0 --end 69530 --referenceName 1 http://localhost:8000 --effects '{"term": "synonymous_variant"}'

# run the CTK against the server
cd ..
cd compliance
./ctk
# View results in the testresults directory

```

Here is an example client that will visualize the frequency of alternate sequence lengths for one of the compliance annotation sets!

https://gist.github.com/david4096/d4020b104a8ee270b2b8

Looking forward to your feedback!

### CODE REVIEW

**Comment by macieksmuga** [comment]
+1. I can't speak to the theoretical part of this PR, but I tested it independently on my system, and it works as promised.

**Comment by jeromekelleher** [comment]
Great work @david4096, I think this completes the server requirements, so the final review and voting should go ahead on the schemas repo.

For this particular PR, we'll need to wait until the schemas are merged into schemas/master and released before we can merge them into master here.

**Comment by dcolligan** [comment]
Ok, I think we're ready to merge this.  Let's discuss during the call.

**Comment by jeromekelleher** [comment]
Great work everyone, this is a major milestone!

**Pull request merged**
