### PR TITLE
202 simulated backend

### PR DESCRIPTION
**Pull request by dcolligan**
First attempt; based off of PR #204 ; haven't modified tests yet; want @jeromekelleher 's feedback.

Issue #202

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This looks good @dcolligan, thanks. I think we should try to push the simulator aspects into the `datamodel.variants` module, and have simulated backend do as little as possible. I would imagine something like the following:
```python
class SimulatedBackend(AbstractBackend):
    def __init__(self, randomSeed, numVariantSets=1, numCalls=1, variantDensity=0.5):
        self._randomSeed = randomSeed
        self._randomGenerator = random.Random(randomSeed)
        for i in range(numVariantSets):
             variantSetId = "simVs{}".format(i)
             seed = self._randomGenerator().randint(0, 2**32)
             variantSet = variants.SimulatedVariantSet(seed, numCalls, variantDensity)
             self._variantSets.append(variantSet)
             self._variantSetIdMap[variantSetId] = variantSet
```
Then, we just inherit all of the search behaviour from the superclass. The `SimulatedVariantSet` class will need to implement `getVariants` like the existing variant sets, but it should be possible to do this easily enough in terms of the functionality that you have here.

In terms of configuration, what you have is perfect right now. We'll want to something a bit more hierarchical as we add more and more simulator parameters, but we can think about that later.

**Comment by dcolligan** [comment]
@jeromekelleher addressed your comments in newest commit

**Comment by jeromekelleher** [comment]
Perfect, thanks. This will make our lives a _lot_ easier for testing.

+1 after you've merged #214 and rebased this.

**Comment by dcolligan** [comment]
@jeromekelleher merge me!

**Pull request merged**
