### PR TITLE
Add robots.txt

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #1136

### CODE REVIEW

**Comment by kozbo** [comment]
You beat me to it @dcolligan :-) Were you able to verify that my configuration file allowed the googlebot through?  I found this test tool that I was using to verify access: https://support.google.com/webmasters/answer/6062598?hl=en

**Comment by dcolligan** [comment]
@kozbo that tool only works on publicly-accessible robots.txt files

**Comment by kozbo** [comment]
@dcolligan ok. Have you found a way to verify that the robots.txt file is doing what it is supposed to do?

**Comment by david4096** [comment]
I verified that it serves the robot.txt from the expected location. I think we want to remove the lines about GoogleBot, the disallow all User agents is sufficient. +1

**Comment by dcolligan** [comment]
@kozbo  I think @david4096 is right here... someone that deploys the server probably doesn't want google indexing it ... the syntax in this latest updates disallows all robots

http://www.robotstxt.org/robotstxt.html

**Comment by dcolligan** [comment]
@kozbo can I get your +1 here?

**Comment by kozbo** [comment]
yes, @dcolligan, sorry for the delay. Looks good, +1

**Pull request merged**
