### PR TITLE
Searching by non-existent callset name...

### PR DESCRIPTION
**Pull request by dcolligan**
... now returns no results instead of a 404

Issue #647

### CODE REVIEW

**Comment by jeromekelleher** [comment]
+1

**Comment by macieksmuga** [comment]
How does this square with compliance tests @hjellinek? Do we need to modify them to suit this?

**Comment by hjellinek** [comment]
The tests are all right.

The test `ReadGroupSetsGetByNameIT.testSearchForBogusNameReturnsEmptyList` actually does what its name implies: the `SearchReadGroupSetsResponse` for a nonexistent name is expected to contain an empty `readGroupSets` list.

In other words, fixing this bug will increase the Ref Server's compliance score.

**Comment by hjellinek** [comment]
p.s. I had already updated the docs in the `documentation` branch of ga4gh/schemas to describe this behavior.

**Pull request merged**
