### PR TITLE
Added configurable host string for server CLI.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Issue #592

### CODE REVIEW

**Comment by dcolligan** [comment]
+1

**Comment by dcolligan** [comment]
Looks like the tests didn't pass... maybe this is causing one of the end to end tests to stall?  Or maybe Travis just borked the test run?

**Comment by jeromekelleher** [comment]
Yes, there was a problem with the end-to-end tests: the OIDC tests require us to open a socket to ``gethostbyname``, so we need to allow connections from outside. Should be fixed now.

**Comment by jeromekelleher** [comment]
@dcolligan merge me!

**Pull request merged**
