### PR TITLE
Gemini integration instructions.

### PR DESCRIPTION
**Pull request by dkucsc**
An example of applying our GA4GH API to an existing and external code base, namely, the Gemini database.

### CODE REVIEW

**Comment by dkucsc** [comment]
I'm going to work on this a bit more and commit again folks, fyi.

**Comment by dkucsc** [comment]
Ok, I hope these changes are good.

**Comment by david4096** [comment]
Since we have https://github.com/BD2KGenomics/ga4gh-gemini I don't think this belongs here, but it suggests to me we should have a "related software" section in the docs.

**Comment by dkucsc** [comment]
Oh I recall now, yes.  [This](https://github.com/dkucsc/mavas/blob/feature/gemini/docs/gemini.md) was done way before [another repo](https://github.com/BD2KGenomics/ga4gh-gemini) was created for the same task.

For now, I think I'll close this pull request after I merge the information into the ga4gh-gemini repo.

**Comment by dkucsc** [comment]
Ok, I merged the disjoint information from https://github.com/dkucsc/mavas/blob/feature/gemini/docs/gemini.md to https://github.com/dkucsc/ga4gh-gemini/blob/master/README.md, and so there's no much more need to keep this, if that's ok.  This pull request taught me about Travis and flake8 and other things too though, so that's good.

**Pull request closed without merging**
