### PR TITLE
Rna branch protobuf update

### PR DESCRIPTION
**Pull request by saupchurch**
this updates the RNA topic branch with latest master in preparation for the RNA server branch conversion to protobuf

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Looks like you've got some issues with the protocol stuff here @saupchurch --- have you added the proto files to git, and imported them in protocol.py?

**Comment by saupchurch** [comment]
This is a topic branch update that just pulls in the changes that have been made to master.  I can do the protobuf conversion here or as a follow-up PR.  @jeromekelleher which would you prefer?  Thanks!

**Comment by jeromekelleher** [comment]
Well we'll have to have the CI checks passing before we can merge into the topic branch, so I think it'll probably be easier to just go ahead with the conversion here rather than hack around the test cases temporarily. It's up to you though, I don't have a strong view on how it should be done.

**Comment by saupchurch** [comment]
this update now includes the conversion to protobuf

**Comment by macieksmuga** [comment]
@jeromekelleher CI passes - do we have your +1 on this merge, or would you rather do the full code review here?

**Comment by jeromekelleher** [comment]
I don't mind @saupchurch, whichever you think makes most sense. It's tricky to review this big a diff, so it probably makes sense to do the review w.r.t master.

+0 --- I haven't reviewed the code, but merge into the topic branch as you see fit

**Comment by saupchurch** [comment]
thanks @jeromekelleher I think we should merge with topic branch and focus on the diff w.r.t. master once all the components are ready to go

@macieksmuga ?

**Comment by macieksmuga** [comment]
Agree. Merging :)

**Pull request merged**
