### PR TITLE
Remove datadir arg

### PR DESCRIPTION
**Pull request by jeromekelleher**
This PR removes the mandatory DATADIR argument from the server CLI, and moves all configuration into the flask config space. This is an essential step towards deployability.

For development, we add a default configuration that we invoke from the CLI that makes  the default data source `ga4gh-example-data`. This should make developers lives easy. We can override this with a config file specified on the command line though.

This will be updated and rebased once #212 has been merged. Feedback welcomed!

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Not sure what happened here and why this got closed. Making a new PR from the same branch.

**Comment by dcolligan** [comment]
You can also reopen the PR...

**Comment by dcolligan** [comment]
Oh, I guess not anymore once you opened the other PR... GitHub only allows one PR per branch, which I suppose is a good thing.

**Comment by jeromekelleher** [comment]
I couldn't find any button to reopen the PR earlier - it didn't seem to offer me the option.

**Comment by dcolligan** [comment]
It's at the bottom of the page, by the green "Comment" button... at least, it is for me.

**Pull request closed without merging**
