### PR TITLE
Improved genotype handling in wormtable variant sets

### PR DESCRIPTION
**Pull request by mbaudrey**
Issue #14

### CODE REVIEW

**Comment by Naburimannu** [comment]
Even though it's trivial, it looks like you'll need to fix the PEP8 whitespace error before Travis will even try the new unit tests.

**Comment by mbaudrey** [comment]
It's taken care of. Sorry about that.

**Comment by jeromekelleher** [comment]
This is excellent, thank @mbaudrey! I've got two suggestions for improving the code layout, but generally I think it's great. 

The first suggestion would be that it would be good to change `convertGenotype` and `convertPhaseset` from static methods of `WormtableVariantSet` to standalone functions, which we might call `convertVCFGenotype` and `convertVCFPhaseset`. The functions are simple standalone bits of functionality, so I think they would be better like this.

For the tests, I think it would be better to group together all of the new test functions into one, which we might go like this:
```python
    def testGenotypeConversion(self):
        # Data is a list of tuples consisting of the VCF genotype and
        # phaseset values followed by the expected GA4GH converted
        # values.
        data = [
            # Genotype with no call
            ("./.", "0", [-1], None),
            # Half call where only the second half is called
            ("./0", "25", [-1], None),
            # ETC
        ]
        for vcfGenotype, vcfPhaseset, ga4ghGenotype, ga4ghPhaseset in data:
            result = variants.convertVCFGenotype(vcfGenotype, vcfPhaseset)
            convertedGenotype, convertedPhaseset = result
            self.assertEqual(ga4ghGenotype, convertedGenotype)
            self.assertEqual(ga4ghPhaseset, convertedPhaseset)
```
This just makes it a bit easier to see all of the test examples in one place, and saves on some repetitive code.

**Comment by diekhans** [comment]
I am over two minds on this.  While the terseness of the coding
this as a loop is nice, it defeats the test cases are
independent goal.

I would be inclined to have a bunch of one-line test cases that
call a common function, would be roughly twice as many lines as
this.

**Comment by jeromekelleher** [comment]
It's a good point, and I agree. The main goal of the above was to make it easier to add new test cases. What about something like this?
```python
    def testGenotypeUnphasedNoCall(self):
        self.verifyGenotypeConversion("./.", "0", [-1], None)
```
This makes it nice and quick to write new test cases without duplicating code.

BTW, this is (as far as I can think) the only example where I think it's better not to have docstring comments on a method. When nosetests runs these in verbose mode, it uses the docstring comments rather than the test method name in the output, which seems less useful. So, here I would definitely document the `verifyGenotypeConversion` method (as this isn't a test case, but a utility function), but leave the actual test cases without docstring comments. 

Does this make sense? I'll make a PR on the style guide writing this up soon.

**Comment by diekhans** [comment]
+16

Agree on the doc string, I fix the behavior of the unittest with
doc strings less than ideal.

Meaningful tests names and then comments that go into more
detail if necessary are the way to go.

**Comment by kerrydc** [comment]
+1

**Comment by jeromekelleher** [comment]
I think we were hoping to update the unit tests here to follow the pattern outlined above before merging. It's not worth backing out of the merge though, as it's mostly right. @mbaudrey, would you mind making a follow-up PR with the changes outlined in my first comment above?

**Comment by Naburimannu** [comment]
@jeromekelleher I thought we should be making the follow-up PR with the changes from @diekhans' comments / your second comment - one function per test case, even if they're just calling a common utility function with different arguments?

**Comment by jeromekelleher** [comment]
Yeah, you're right, that was confusing! What I meant to say was, update to have tests like
```python
    def testGenotypeUnphasedNoCall(self):
        self.verifyGenotypeConversion("./.", "0", [-1], None)
```
I think it would also be good to change `convertVCFGenotype` to a function, since it doesn't depend on the class in any way. Does this make sense @mbaudrey?

**Comment by mbaudrey** [comment]
Yes, I can make a follow up PR. To clarify, both convertVCFGenotype and
convertVCFPhaseset should be standalone functions? And should they still be
in variants.py or is there a better place to put them?

**Comment by jeromekelleher** [comment]
Yes, both should be standalone, and variants.py is where they should live. Thank @mbaudrey!

**Comment by diekhans** [comment]
It's nice to have classes/modules specific to functional areas
to place some standalone functions.  Agree it doesn't belong in
the worm table module, but don't know the code structure well enough
to suggest better.

**Comment by kerrydc** [comment]
I'm doing this in my Tabix PR that should be submitted this afternoon.
Kerry

**Pull request merged**
