### PR TITLE
Initial experimental URL code.

### PR DESCRIPTION
**Pull request by jeromekelleher**
-1, for discussion only.

This is intended to illustrate the design discussed in  #1045. Key differences to current code:

1. We only read in the file ``metadata.json`` to find readGroupSets. We no longer depend on globbing files in the directory.
2. The ``name`` field is now stored in the ``metadata.json`` and not derived from the filename. Going forward, we shouldn't assume anything about the structure of filenames (beyond reasonable stuff like them being unique within dataset). We should move towards storing all the stuff we need to know about a readGroupSet here rather than deriving it from the BAM file at run time.
3. Index is supplied separately to allow for reading from URLs.

I would view the ``metadata.json`` as an interrim step towards storing all the metadata in a database, and applying this principle right across the data repo.

Thoughts?

### CODE REVIEW

**Comment by jeromekelleher** [comment]
No thoughts at all from anyone on this? I'll assume that everyone thinks this design is perfect in that case.

**Comment by diekhans** [comment]
Looks very sane to me

**Comment by david4096** [comment]
@jeromekelleher Yes, this is a great approach! It places the requirement on the repo manager that it can add and remove elements from the `metadata.json`, and for that reason it may simplify things to make it a map of identifiers to objects as opposed to a list of objects.

Here is the metadata.json I used to test this PR:
```
[
  {"name": "hello",
  "dataUrl": "http://ga4ghstore.blob.core.windows.net/testing/HG00096.bam",
  "indexUrl": "ga4gh-example-data/datasets/1kg-p3-subset/reads/HG00096.bam.bai"}
]
```

I had some issues using pysams remote file access reliably. You can take a look [here](http://nbviewer.jupyter.org/gist/david4096/95c0b187b67a960780f0715863955e48). I found I was getting 500 errors using this PR. Pysam fails with an IO error saying the file is truncated. I'm hoping it's merely my naivete about using pysam properly that caused these issues. I was able to download the file locally and it worked reliably, but when using a remote file I would intermittently receive truncated file errors.

It may be possible that these edited BAMs are a special case that the remote code fails on. I will repeat this exercise with full BAM files to see if the same problem crops up. You don't have to refresh the file handle after a `fetch` or something, do you?

**Comment by macieksmuga** [comment]
I very much like the general direction of this, but I'm wondering - is there some metadata already contained within the BAM headers that we'd be needlessly replicating in the JSON this way?

**Comment by jeromekelleher** [comment]
I think we should just read the BAM headers at import time and store the useful data in a format that's easy to work with. Parsing text headers is slow and complicated, and shouldn't be done at run-time.

I'm closing this PR as it has been superseded by #1079.

**Pull request closed without merging**
