### PR TITLE
Bump version to 0.1.2

### PR DESCRIPTION
**Pull request by dcolligan**

### CODE REVIEW

**Comment by dcolligan** [comment]
This bugfix release will address the following issues:
#455 - bugs in reads/search call (pysam calls not sanitized, wrong number of arguments to getReadAlignments)
#433 - bugs in paging code for reads and variants

**Comment by dcolligan** [comment]
I've manually verified that both of the above-mentioned bugs are fixed in this branch

**Comment by jeromekelleher** [comment]
Great work @dcolligan, thanks. I think we're ready to roll 0.1.2 now.

+1. Merging.

**Comment by dcolligan** [comment]
done 

https://github.com/ga4gh/server/releases/tag/v0.1.2

https://pypi.python.org/pypi/ga4gh/0.1.2

**Comment by jeromekelleher** [comment]
Excellent! OK, we just need to merge release-0.1 into the stable branch now, and we're done I think.

**Comment by dcolligan** [comment]
Done

**Pull request merged**
