### PR TITLE
added kwargs field to protocol __init__ methods

### PR DESCRIPTION
**Pull request by dcolligan**
I'm not sure if we want to merge this now or later, since we can't really run `process_schemas.py` successfully to generate a new `_protocol_definitions.py` until the schemas repo is fixed

Issue #372

### CODE REVIEW

**Comment by diekhans** [comment]
What is the PR to fix the schema repo fix?

**Comment by dcolligan** [comment]
#379

**Comment by diekhans** [comment]
Sorry, I am confused. Is there a PR against schemas to fix a problem. #379 is against server.
I can help push a schemas PR forwards.  

You guys get to have your own process for accepting pulls. Just keep it moving.

**Comment by dcolligan** [comment]
https://github.com/ga4gh/schemas/pull/293
and
https://github.com/ga4gh/schemas/pull/292

**Comment by diekhans** [comment]
Danny Colligan <notifications@github.com> writes:
> https://github.com/ga4gh/schemas/pull/292

This one impacts the functionality and is under debate. Can a PR
that keeps the 3-state values and just fixes the schema bug be
created?

**Comment by dcolligan** [comment]
No, because the bug is the issue under discussion.

**Comment by dcolligan** [comment]
filing another PR for this

**Pull request closed without merging**
