### PR TITLE
Fixed issues with new flake version.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Minimal changes to fix flake8 issues.

This should be uncontroversial, so lets try to merge it ASAP and we can then rebase any existing PRs.

### CODE REVIEW

**Comment by Naburimannu** [comment]
+!

**Comment by jeromekelleher** [comment]
Can you merge please @Naburimannu?

**Comment by Naburimannu** [comment]
Nope, I don't have collaborator access.

**Comment by dcolligan** [comment]
@jeromekelleher can you grant @Naburimannu write access?

**Comment by jeromekelleher** [comment]
No, I don't have admin access to the teams either.

**Comment by dcolligan** [comment]
@jeromekelleher is now an admin so he can grant @Naburimannu write access

**Pull request merged**
