### PR TITLE
Removed pointless docs/source dir.

### PR DESCRIPTION
**Pull request by jeromekelleher**

### CODE REVIEW

**Comment by dcolligan** [comment]
Why was it there in the first place?  Is this some kind of sphinx best practice?  Or is it actually completely unnecessary and un-sphinx-idiomatic?

**Comment by jeromekelleher** [comment]
I'm not sure why it ended up in there --- @shajoezhu, I think you set this up initially?.

**Comment by shajoezhu** [comment]
Hi Danny and Jerome,

I believe this was because how I usually set up my files, where I have my source code in one folder, and images under another folder, and both are under the folder docs.

Best
Joe

**Comment by shajoezhu** [comment]
+1

**Pull request merged**
