### PR TITLE
RNA Quantification BioSample ID

### PR DESCRIPTION
**Pull request by david4096**
This PR allows RNA quantifications to be tagged and queried by biosample identifiers. It adds an option to use the CLI to tag quantifications using BioSample names. The test data has not been updated.

Prepare compliance has been updated to tag the rna quantification with HG00096's biosample ID.

https://github.com/ga4gh/schemas/pull/705

### CODE REVIEW

**Comment by kozbo** [comment]
Tested out on my local server, works for me. +1

**Comment by kozbo** [comment]
@david4096 perhaps a squash in in order?
@dcolligan If this looks good then we can merge the schema and server changes.

**Comment by dcolligan** [comment]
+1 after squashing into one commit

**Comment by kozbo** [comment]
tested again with the following:
```
python repo_dev.py add-biosample ga4gh-compliance-data/registry.db  brca1 bio-1 '{"individualId": "WyIxa2dlbm9tZXMiLCJpIiwiSEcwMDA5NiJd", "id": "WyIxa2dlbm9tZXMiLCJiIiwiSEcwMDA5NiJd", "datasetId": "WyIxa2dlbm9tZXMiXQ", "name": "HG00096"}'
```
and then 
```
python repo_dev.py add-rnaquantification  --bioSampleName HG00096 --readGroupSetName HG00096 --featureSetNames gencodev19,ga4gh-compliance-data/cgd -n abundance -d "kallisto output" -t ga4gh-compliance-data/rnaseq.db ga4gh-example-data/abundance.tsv kallisto ga4gh-compliance-data/registry.db  brca1
```
Unfortunately I chose a very large tsv file to add, and it has been running for over an hour. Note that I used two feature sets too, so that is probably slowing it down too. Anyway, it looks like it worked, so +1

**Comment by dcolligan** [comment]
applied in #1425

**Pull request closed without merging**
