### PR TITLE
Added directions about process_schemas.py to docs

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #373

### CODE REVIEW

**Comment by dcolligan** [comment]
@diekhans can I get your +1 on this, since you filed the issue?

**Comment by jeromekelleher** [comment]
Looks good @dcolligan, although I feel like it could be fleshed out a bit. I agree @diekhans should have the last word though.

**Comment by jeromekelleher** [comment]
ps. apologies for a very vague comment! I'm fine with this as-is if @diekhans is happy with it.

**Comment by diekhans** [comment]
I think we need to explain what `desired version' means in the contact of the server.

**Comment by dcolligan** [comment]
Alright, added a bit about that.  If you don't like this phrasing @diekhans please specify how you would prefer it.

**Comment by diekhans** [comment]
This doesn;t really say what desiredVersion is:
    Where ``desiredVersion`` is the version that will be written to the ``_protocol_definitions.py`` file.

is it a git tag, sha1 hash, etc.  what are the valid values?

**Comment by dcolligan** [comment]
@diekhans updated the code based on your concerns

**Comment by dcolligan** [comment]
@diekhans can I get a review here?

**Comment by diekhans** [comment]
looks good

**Pull request merged**
