### PR TITLE
Added example iPython notebook under scripts/

### PR DESCRIPTION
**Pull request by hershman**
Addresses Issue #662

### CODE REVIEW

**Comment by dcolligan** [comment]
can we get a review from someone that uses iPython?  I'm not that familiar with it...

**Comment by jeromekelleher** [comment]
Looks pretty cool @hershman, but I think we'll need a bit of time to try it out and digest it.

We should change the filename though... spaces in filenames are bad.

**Comment by hershman** [comment]
Since Github doesn't do a great job of previewing ipython notebooks, here is the current content:



# GA4GH IPython Example Notebook

This notebook provides an overview of how to call a the GA4GH reference server from an iPython notebook.  Before running this notebook:

1. git clone https://github.com/ga4gh/server.git -b develop
2. Download the example data (if $scripts/download\_data.py$ doens't work, wget http://www.well.ox.ac.uk/~jk/ga4gh-example-data-v3.0.tar and tar -xvf in the server/ directory
3. Launch an instance of the reference server on localhost ("python server_dev.py")

## Connect to GA4GH Server


    import ga4gh.client
    baseURL = "http://localhost:8000"
    client = ga4gh.client.HttpClient(baseURL)

Great! Now we can run calls to query ReferenceSets, References, Datasets, VariantSets, CallSets, Variants, ReadGroups, ReadGroupSets, & Reads

## Search/Get ReferenceSets

ReferenceSets are lists of References.  Think of them like the genome version (ie. grch37, hg19).  This NCBI Taxon Id for our human dataset is:


    results = client.searchReferenceSets()
    for result in results:
        print result.ncbiTaxonId
        referenceSetId = result.id

    9606



    referenceSet = client.getReferenceSet(referenceSetId)
    print referenceSet

    ReferenceSet({"name": null, "sourceURI": "TODO", "assemblyId": "TODO", "sourceAccessions": [], "ncbiTaxonId": 9606, "isDerived": false, "id": "R1JDaDM4LXN1YnNldA==", "md5checksum": "234ea63052f999c21c2bdb6f60e61038", "description": "TODO"})


## Search/Get References 

The References endpoints let you access DNA sequences. The example dataset is from subsets of the first 3 chromosomes:


    results = client.searchReferences(referenceSetId)
    for result in results:
        print result.name, result.length
        referenceId = result.id

    1 138395
    2 32403
    3 81617



    reference = client.getReference(referenceId)
    print reference

    Reference({"name": "3", "sourceURI": "http://www.ebi.ac.uk/ena/data/view/CM000665.2%26range=0-81617&display=fasta", "sourceAccessions": ["CM000665.2.subset"], "sourceDivergence": null, "length": 81617, "md5checksum": "0680724fdd32e4dba0c14db5cef24f1e", "isDerived": false, "id": "R1JDaDM4LXN1YnNldDoz", "ncbiTaxonId": 9606})


In addition to fetching metadata about the reference, you can access the base sequence:


    client.listReferenceBases(referenceId, start=10000, end=10100)




    u'CTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTCACCCTACCCTAACCCTAACCCTAACCCTCACCCTCACCCTCACTCAACC'



## Search/Get Dataset


    results = client.searchDatasets()
    for result in results:
        print result.name
        datasetId =  result.id

    1kg-p3-subset



    dataset = client.getDataset(datasetId)
    print dataset

    Dataset({"description": null, "name": "1kg-p3-subset", "id": "MWtnLXAzLXN1YnNldA=="})


## Search/Get VariantSets


    results = client.searchVariantSets(datasetId)
    for result in results:
        print result.name
        variantSetId = result.id

    mvncall



    variantSet = client.getVariantSet(variantSetId)
    print variantSet

    VariantSet({"name": "mvncall", "referenceSetId": "", "id": "MWtnLXAzLXN1YnNldDptdm5jYWxs", "datasetId": "MWtnLXAzLXN1YnNldA==", "metadata": [{"info": {}, "description": "", "number": "1", "value": "VCFv4.1", "key": "version", "type": "String", "id": ""}, {"info": {}, "description": "Confidence interval around END for imprecise variants", "number": "2", "value": "", "key": "INFO.CIEND", "type": "Integer", "id": ""}, {"info": {}, "description": "Confidence interval around POS for imprecise variants", "number": "2", "value": "", "key": "INFO.CIPOS", "type": "Integer", "id": ""}, {"info": {}, "description": "Source call set.", "number": "1", "value": "", "key": "INFO.CS", "type": "String", "id": ""}, {"info": {}, "description": "End coordinate of this variant", "number": "1", "value": "", "key": "INFO.END", "type": "Integer", "id": ""}, {"info": {}, "description": "Imprecise structural variation", "number": "0", "value": "", "key": "INFO.IMPRECISE", "type": "Flag", "id": ""}, {"info": {}, "description": "Merged calls.", "number": ".", "value": "", "key": "INFO.MC", "type": "String", "id": ""}, {"info": {}, "description": "Mobile element info of the form NAME,START,END<POLARITY; If there is only 5' OR 3' support for this call, will be NULL NULL for START and END", "number": "4", "value": "", "key": "INFO.MEINFO", "type": "String", "id": ""}, {"info": {}, "description": "Mitochondrial end coordinate of inserted sequence", "number": "1", "value": "", "key": "INFO.MEND", "type": "Integer", "id": ""}, {"info": {}, "description": "Estimated length of mitochondrial insert", "number": "1", "value": "", "key": "INFO.MLEN", "type": "Integer", "id": ""}, {"info": {}, "description": "Mitochondrial start coordinate of inserted sequence", "number": "1", "value": "", "key": "INFO.MSTART", "type": "Integer", "id": ""}, {"info": {}, "description": "SV length. It is only calculated for structural variation MEIs. For other types of SVs; one may calculate the SV length by INFO:END-START+1, or by finding the difference between lengthes of REF and ALT alleles", "number": ".", "value": "", "key": "INFO.SVLEN", "type": "Integer", "id": ""}, {"info": {}, "description": "Type of structural variant", "number": "1", "value": "", "key": "INFO.SVTYPE", "type": "String", "id": ""}, {"info": {}, "description": "Precise Target Site Duplication for bases, if unknown, value will be NULL", "number": "1", "value": "", "key": "INFO.TSD", "type": "String", "id": ""}, {"info": {}, "description": "Total number of alternate alleles in called genotypes", "number": "A", "value": "", "key": "INFO.AC", "type": "Integer", "id": ""}, {"info": {}, "description": "Estimated allele frequency in the range (0,1)", "number": "A", "value": "", "key": "INFO.AF", "type": "Float", "id": ""}, {"info": {}, "description": "Number of samples with data", "number": "1", "value": "", "key": "INFO.NS", "type": "Integer", "id": ""}, {"info": {}, "description": "Total number of alleles in called genotypes", "number": "1", "value": "", "key": "INFO.AN", "type": "Integer", "id": ""}, {"info": {}, "description": "Allele frequency in the EAS populations calculated from AC and AN, in the range (0,1)", "number": "A", "value": "", "key": "INFO.EAS_AF", "type": "Float", "id": ""}, {"info": {}, "description": "Allele frequency in the EUR populations calculated from AC and AN, in the range (0,1)", "number": "A", "value": "", "key": "INFO.EUR_AF", "type": "Float", "id": ""}, {"info": {}, "description": "Allele frequency in the AFR populations calculated from AC and AN, in the range (0,1)", "number": "A", "value": "", "key": "INFO.AFR_AF", "type": "Float", "id": ""}, {"info": {}, "description": "Allele frequency in the AMR populations calculated from AC and AN, in the range (0,1)", "number": "A", "value": "", "key": "INFO.AMR_AF", "type": "Float", "id": ""}, {"info": {}, "description": "Allele frequency in the SAS populations calculated from AC and AN, in the range (0,1)", "number": "A", "value": "", "key": "INFO.SAS_AF", "type": "Float", "id": ""}, {"info": {}, "description": "Total read depth; only low coverage data were counted towards the DP, exome data were not used", "number": "1", "value": "", "key": "INFO.DP", "type": "Integer", "id": ""}, {"info": {}, "description": "Ancestral Allele. Format: AA|REF|ALT|IndelType. AA: Ancestral allele, REF:Reference Allele, ALT:Alternate Allele, IndelType:Type of Indel (REF, ALT and IndelType are only defined for indels)", "number": "1", "value": "", "key": "INFO.AA", "type": "String", "id": ""}, {"info": {}, "description": "indicates what type of variant the line represents", "number": ".", "value": "", "key": "INFO.VT", "type": "String", "id": ""}, {"info": {}, "description": "indicates whether a variant is within the exon pull down target boundaries", "number": "0", "value": "", "key": "INFO.EX_TARGET", "type": "Flag", "id": ""}, {"info": {}, "description": "indicates whether a site is multi-allelic", "number": "0", "value": "", "key": "INFO.MULTI_ALLELIC", "type": "Flag", "id": ""}]})


## Search/Get Callset

Callsets apply to the samples within a dataset


    results = client.searchCallSets(variantSetId)
    for result in results:
        print result.name
        callSetId =  result.id

    HG00096
    HG00533
    HG00534



    callset = client.getCallSet(callSetId)
    print callset

    CallSet({"info": {}, "updated": 1444663564000, "name": "HG00534", "created": 1444663564000, "sampleId": "HG00534", "variantSetIds": ["MWtnLXAzLXN1YnNldDptdm5jYWxs"], "id": "MWtnLXAzLXN1YnNldDptdm5jYWxsOkhHMDA1MzQ="})


## Search/Get Variants


    results = client.searchVariants(variantSetId, referenceName = "1")
    for result in results:
        print result.referenceName, result.start, result.names[0]
        variantId = result.id

    1 10176 rs367896724
    1 10234 rs540431307
    1 10351 rs555500075
    1 10504 rs548419688
    1 10505 rs568405545
    1 10510 rs534229142
    1 10538 rs537182016
    1 10541 rs572818783
    1 10578 rs538322974
    1 10615 rs376342519
    1 10641 rs558604819
    1 11007 rs575272151
    1 11011 rs544419019
    1 11062 rs561109771
    1 13010 rs574746232
    1 13109 rs540538026
    1 13115 rs62635286
    1 13117 rs200579949
    1 13155 rs552314247
    1 13258 rs562993331
    1 13272 rs531730856
    1 13283 rs548333521
    1 13288 rs568318295
    1 13288 rs538791886
    1 13312 SNiP
    1 137977 rs529853750
    1 138016 rs540060493
    1 138040 rs560358882
    1 138347 rs532293705
    1 138378 rs552079736
    1 138395 rs568894656



    variant = client.getVariant(variantId)
    print variant

    Variant({"info": {"EUR_AF": ["0.00889999978244"], "SAS_AF": ["0.00410000002012"], "AC": ["0"], "AA": [".|||"], "AF": ["0.00319488998502"], "AFR_AF": ["0.00079999997979"], "AMR_AF": ["0.00289999996312"], "AN": ["6"], "VT": ["SNP"], "EAS_AF": ["0.0"], "NS": ["2504"], "DP": ["28809"]}, "updated": 1444663564000, "end": 138396, "calls": [{"info": {}, "genotype": [0, 0], "callSetId": "MWtnLXAzLXN1YnNldDptdm5jYWxsOkhHMDAwOTY=", "phaseset": "*", "genotypeLikelihood": [], "callSetName": "HG00096"}, {"info": {}, "genotype": [0, 0], "callSetId": "MWtnLXAzLXN1YnNldDptdm5jYWxsOkhHMDA1MzM=", "phaseset": "*", "genotypeLikelihood": [], "callSetName": "HG00533"}, {"info": {}, "genotype": [0, 0], "callSetId": "MWtnLXAzLXN1YnNldDptdm5jYWxsOkhHMDA1MzQ=", "phaseset": "*", "genotypeLikelihood": [], "callSetName": "HG00534"}], "created": 1444663564000, "variantSetId": "MWtnLXAzLXN1YnNldDptdm5jYWxs", "referenceBases": "G", "start": 138395, "names": ["rs568894656"], "alternateBases": ["A"], "referenceName": "1", "id": "MWtnLXAzLXN1YnNldDptdm5jYWxsOjE6MTM4Mzk1OmYzNDEzYmQxNWM1Y2JjMjhkMWJiNjY4ZjhlYzY3NzMy"})


## Search/Get Readgroupsets


    results = client.searchReadGroupSets(datasetId)
    for result in results:
        print result.name
        readGroupSetId = result.id
        readGroupId = result.readGroups[0].id

    HG00096
    HG00533
    HG00534



    readgroupset = client.getReadGroupSet(readGroupSetId)
    print readgroupset

    ReadGroupSet({"readGroups": [{"info": {}, "updated": 1444697504850, "predictedInsertSize": 486, "stats": {"unalignedReadCount": -1, "alignedReadCount": -1, "baseCount": null}, "description": "SRP001293", "created": 1444697504850, "programs": [{"commandLine": "bwa index -a bwtsw $reference_fasta", "prevProgramId": null, "id": "bwa_index", "version": "0.5.9-r16", "name": "bwa"}, {"commandLine": "bwa aln -q 15 -f $sai_file $reference_fasta $fastq_file\tPP:bwa_index", "prevProgramId": null, "id": "bwa_aln_fastq", "version": "0.5.9-r16", "name": "bwa"}, {"commandLine": "bwa sampe -a 1458 -r $rg_line -f $sam_file $reference_fasta $sai_file(s) $fastq_file(s)\tPP:bwa_aln_fastq", "prevProgramId": null, "id": "bwa_sam", "version": "0.5.9-r16", "name": "bwa"}, {"commandLine": "samtools view -bSu $sam_file | samtools sort -n -o - samtools_nsort_tmp | samtools fixmate /dev/stdin /dev/stdout | samtools sort -o - samtools_csort_tmp | samtools fillmd -u - $reference_fasta > $fixed_bam_file\tPP:bwa_sam", "prevProgramId": null, "id": "sam_to_fixed_bam", "version": "0.1.17 (r973:277)", "name": "samtools"}, {"commandLine": "java $jvm_args -jar GenomeAnalysisTK.jar -T RealignerTargetCreator -R $reference_fasta -o $intervals_file -known $known_indels_file(s) \tPP:sam_to_fixed_bam", "prevProgramId": null, "id": "gatk_target_interval_creator", "version": "1.2-29-g0acaf2d", "name": "GenomeAnalysisTK"}, {"commandLine": "java $jvm_args -jar GenomeAnalysisTK.jar -T IndelRealigner -R $reference_fasta -I $bam_file -o $realigned_bam_file -targetIntervals $intervals_file -known $known_indels_file(s) -LOD 0.4 -model KNOWNS_ONLY -compress 0 --disable_bam_indexing\tPP:gatk_target_interval_creator", "prevProgramId": null, "id": "bam_realignment_around_known_indels", "version": "1.2-29-g0acaf2d", "name": "GenomeAnalysisTK"}, {"commandLine": "java $jvm_args -jar GenomeAnalysisTK.jar -T CountCovariates -R $reference_fasta -I $bam_file -recalFile $bam_file.recal_data.csv -knownSites $known_sites_file(s) -l INFO -L '1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20;21;22;X;Y;MT' -cov ReadGroupCovariate -cov QualityScoreCovariate -cov CycleCovariate -cov DinucCovariate\tPP:bam_realignment_around_known_indels", "prevProgramId": null, "id": "bam_count_covariates", "version": "1.2-29-g0acaf2d", "name": "GenomeAnalysisTK"}, {"commandLine": "java $jvm_args -jar GenomeAnalysisTK.jar -T TableRecalibration -R $reference_fasta -recalFile $bam_file.recal_data.csv -I $bam_file -o $recalibrated_bam_file -l INFO -compress 0 --disable_bam_indexing\tPP:bam_count_covariates", "prevProgramId": null, "id": "bam_recalibrate_quality_scores", "version": "1.2-29-g0acaf2d", "name": "GenomeAnalysisTK"}, {"commandLine": "samtools calmd -Erb $bam_file $reference_fasta > $bq_bam_file\tPP:bam_recalibrate_quality_scores", "prevProgramId": null, "id": "bam_calculate_bq", "version": "0.1.17 (r973:277)", "name": "samtools"}, {"commandLine": "java $jvm_args -jar MergeSamFiles.jar INPUT=$bam_file(s) OUTPUT=$merged_bam VALIDATION_STRINGENCY=SILENT\tPP:bam_calculate_bq", "prevProgramId": null, "id": "bam_merge", "version": "1.53", "name": "picard"}, {"commandLine": "java $jvm_args -jar MarkDuplicates.jar INPUT=$bam_file OUTPUT=$markdup_bam_file ASSUME_SORTED=TRUE METRICS_FILE=/dev/null VALIDATION_STRINGENCY=SILENT\tPP:bam_merge", "prevProgramId": null, "id": "bam_mark_duplicates", "version": "1.53", "name": "picard"}, {"commandLine": "java $jvm_args -jar MergeSamFiles.jar INPUT=$bam_file(s) OUTPUT=$merged_bam VALIDATION_STRINGENCY=SILENT\tPP:bam_mark_duplicates", "prevProgramId": null, "id": "bam_merge.1", "version": "1.53", "name": "picard"}], "sampleId": "HG00534", "experiment": {"info": {}, "selection": null, "recordCreateTime": "2015-10-13T00:51:44Z", "description": "SRP001293", "platformUnit": null, "sequencingCenter": "BGI", "molecule": null, "instrumentModel": "ILLUMINA", "library": "HUMwfmREKDIAAPEI-4", "name": null, "strategy": null, "libraryLayout": null, "recordUpdateTime": "2015-10-13T00:51:44Z", "runTime": null, "id": "MWtnLXAzLXN1YnNldDpIRzAwNTM0OkVSUjAyMDIzODpleHBlcmltZW50", "instrumentDataFile": null}, "referenceSetId": "R1JDaDM4LXN1YnNldA==", "id": "MWtnLXAzLXN1YnNldDpIRzAwNTM0OkVSUjAyMDIzOA==", "datasetId": "MWtnLXAzLXN1YnNldA==", "name": "ERR020238"}], "stats": {"unalignedReadCount": 36, "alignedReadCount": 2933, "baseCount": null}, "id": "MWtnLXAzLXN1YnNldDpIRzAwNTM0", "datasetId": "MWtnLXAzLXN1YnNldA==", "name": "HG00534"})


## Get ReadGroups


    readgroup = client.getReadGroup(readGroupId)
    print readgroup

    ReadGroup({"info": {}, "updated": 1444697504850, "predictedInsertSize": 486, "stats": {"unalignedReadCount": -1, "alignedReadCount": -1, "baseCount": null}, "description": "SRP001293", "created": 1444697504850, "programs": [{"commandLine": "bwa index -a bwtsw $reference_fasta", "prevProgramId": null, "id": "bwa_index", "version": "0.5.9-r16", "name": "bwa"}, {"commandLine": "bwa aln -q 15 -f $sai_file $reference_fasta $fastq_file\tPP:bwa_index", "prevProgramId": null, "id": "bwa_aln_fastq", "version": "0.5.9-r16", "name": "bwa"}, {"commandLine": "bwa sampe -a 1458 -r $rg_line -f $sam_file $reference_fasta $sai_file(s) $fastq_file(s)\tPP:bwa_aln_fastq", "prevProgramId": null, "id": "bwa_sam", "version": "0.5.9-r16", "name": "bwa"}, {"commandLine": "samtools view -bSu $sam_file | samtools sort -n -o - samtools_nsort_tmp | samtools fixmate /dev/stdin /dev/stdout | samtools sort -o - samtools_csort_tmp | samtools fillmd -u - $reference_fasta > $fixed_bam_file\tPP:bwa_sam", "prevProgramId": null, "id": "sam_to_fixed_bam", "version": "0.1.17 (r973:277)", "name": "samtools"}, {"commandLine": "java $jvm_args -jar GenomeAnalysisTK.jar -T RealignerTargetCreator -R $reference_fasta -o $intervals_file -known $known_indels_file(s) \tPP:sam_to_fixed_bam", "prevProgramId": null, "id": "gatk_target_interval_creator", "version": "1.2-29-g0acaf2d", "name": "GenomeAnalysisTK"}, {"commandLine": "java $jvm_args -jar GenomeAnalysisTK.jar -T IndelRealigner -R $reference_fasta -I $bam_file -o $realigned_bam_file -targetIntervals $intervals_file -known $known_indels_file(s) -LOD 0.4 -model KNOWNS_ONLY -compress 0 --disable_bam_indexing\tPP:gatk_target_interval_creator", "prevProgramId": null, "id": "bam_realignment_around_known_indels", "version": "1.2-29-g0acaf2d", "name": "GenomeAnalysisTK"}, {"commandLine": "java $jvm_args -jar GenomeAnalysisTK.jar -T CountCovariates -R $reference_fasta -I $bam_file -recalFile $bam_file.recal_data.csv -knownSites $known_sites_file(s) -l INFO -L '1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20;21;22;X;Y;MT' -cov ReadGroupCovariate -cov QualityScoreCovariate -cov CycleCovariate -cov DinucCovariate\tPP:bam_realignment_around_known_indels", "prevProgramId": null, "id": "bam_count_covariates", "version": "1.2-29-g0acaf2d", "name": "GenomeAnalysisTK"}, {"commandLine": "java $jvm_args -jar GenomeAnalysisTK.jar -T TableRecalibration -R $reference_fasta -recalFile $bam_file.recal_data.csv -I $bam_file -o $recalibrated_bam_file -l INFO -compress 0 --disable_bam_indexing\tPP:bam_count_covariates", "prevProgramId": null, "id": "bam_recalibrate_quality_scores", "version": "1.2-29-g0acaf2d", "name": "GenomeAnalysisTK"}, {"commandLine": "samtools calmd -Erb $bam_file $reference_fasta > $bq_bam_file\tPP:bam_recalibrate_quality_scores", "prevProgramId": null, "id": "bam_calculate_bq", "version": "0.1.17 (r973:277)", "name": "samtools"}, {"commandLine": "java $jvm_args -jar MergeSamFiles.jar INPUT=$bam_file(s) OUTPUT=$merged_bam VALIDATION_STRINGENCY=SILENT\tPP:bam_calculate_bq", "prevProgramId": null, "id": "bam_merge", "version": "1.53", "name": "picard"}, {"commandLine": "java $jvm_args -jar MarkDuplicates.jar INPUT=$bam_file OUTPUT=$markdup_bam_file ASSUME_SORTED=TRUE METRICS_FILE=/dev/null VALIDATION_STRINGENCY=SILENT\tPP:bam_merge", "prevProgramId": null, "id": "bam_mark_duplicates", "version": "1.53", "name": "picard"}, {"commandLine": "java $jvm_args -jar MergeSamFiles.jar INPUT=$bam_file(s) OUTPUT=$merged_bam VALIDATION_STRINGENCY=SILENT\tPP:bam_mark_duplicates", "prevProgramId": null, "id": "bam_merge.1", "version": "1.53", "name": "picard"}], "sampleId": "HG00534", "experiment": {"info": {}, "selection": null, "recordCreateTime": "2015-10-13T00:51:44Z", "description": "SRP001293", "platformUnit": null, "sequencingCenter": "BGI", "molecule": null, "instrumentModel": "ILLUMINA", "library": "HUMwfmREKDIAAPEI-4", "name": null, "strategy": null, "libraryLayout": null, "recordUpdateTime": "2015-10-13T00:51:44Z", "runTime": null, "id": "MWtnLXAzLXN1YnNldDpIRzAwNTM0OkVSUjAyMDIzODpleHBlcmltZW50", "instrumentDataFile": null}, "referenceSetId": "R1JDaDM4LXN1YnNldA==", "id": "MWtnLXAzLXN1YnNldDpIRzAwNTM0OkVSUjAyMDIzOA==", "datasetId": "MWtnLXAzLXN1YnNldA==", "name": "ERR020238"})


## Get Reads


    results = client.searchReads([readGroupId], referenceId)
    for i, result in enumerate(results):
        readId = result.id
    print "%d reads in readgroup id = %s on chrom id = %s" % (i, readGroupId, referenceId)

    997 reads in readgroup id = MWtnLXAzLXN1YnNldDpIRzAwNTM0OkVSUjAyMDIzOA== on chrom id = R1JDaDM4LXN1YnNldDoz



    print result

    ReadAlignment({"info": {"MD": ["15A75"], "NM": ["1"], "AM": ["37"], "RG": ["ERR020238"], "MQ": ["60"], "BQ": ["@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"], "SM": ["37"], "X0": ["1"], "X1": ["0"], "XT": ["U"]}, "duplicateFragment": false, "readGroupId": "MWtnLXAzLXN1YnNldDpIRzAwNTM0OkVSUjAyMDIzOA==", "alignedQuality": [35, 37, 40, 39, 39, 41, 41, 39, 42, 43, 42, 42, 44, 43, 41, 44, 40, 42, 37, 43, 42, 40, 41, 41, 41, 43, 41, 42, 38, 43, 41, 41, 44, 44, 42, 44, 39, 42, 42, 44, 43, 43, 42, 45, 42, 43, 43, 42, 42, 43, 42, 42, 39, 44, 44, 44, 40, 44, 43, 42, 42, 43, 42, 44, 43, 42, 43, 44, 41, 41, 43, 42, 41, 41, 41, 42, 41, 40, 41, 42, 41, 40, 40, 40, 39, 41, 38, 38, 37, 37, 35], "failedVendorQualityChecks": false, "fragmentName": "ERR020238.14295398", "readNumber": 0, "properPlacement": true, "fragmentId": "TODO", "supplementaryAlignment": false, "numberReads": 2, "fragmentLength": -477, "secondaryAlignment": false, "alignedSequence": "CAAGGGGGTGCAAGGTTATGCACAAAGGAATACCACAATCATATTACAATGAATCCTCCTACAAGGCAGATTATACTGACCTACAAGCTTC", "id": "MWtnLXAzLXN1YnNldDpIRzAwNTM0OkVSUjAyMDIzODpFUlIwMjAyMzguMTQyOTUzOTg=", "alignment": {"position": {"position": 75068, "strand": "NEG_STRAND", "referenceName": "3"}, "cigar": [{"referenceSequence": null, "operation": "ALIGNMENT_MATCH", "operationLength": 91}], "mappingQuality": 60}, "nextMatePosition": {"position": 74681, "strand": "POS_STRAND", "referenceName": "3"}})

**Comment by jeromekelleher** [comment]
It looks super cool, and is great addition. Here's some quick comments (more later).

Minor issues:

- We should stick to python3 syntax for print(). Can we put in a ``__future__`` import in the notebook?

-Maybe it would be a bit more intuitive if we said something like

```python
referenceSets = list(client.searchReferenceSets())
referenceSet = referenceSet[0]
print("NCBI Taxon Id = ", referenceSet.ncbiTaxonId)
```

**Comment by jeromekelleher** [comment]
This looks great, thanks @hershman. I think we could make things a bit more intuitive if we made lists of the search results. For example, we might have

```python
readGroupSets = list(client.searchReadGroupSets(dataset.id))
for readGroupSet in readGroupSets:
    print(readGroupSet.name, readGroupSet.id)
readGroup = readGroupSets[0].readGroups[0]
```
etc.

Also, we're tending to use the ``format`` method over string interpolation so it would be nice to be consistent here. I.e., we'd have
```python
print("{} reads in readgroup id = {} on reference id = {}".format(
    len(reads), readGroup.id, reference.id)
```

Otherwise, looks good to me!

**Comment by jeromekelleher** [comment]
How is this looking to you @hershman? If there it's not too much work, it would be nice to change the notebook to take the style notes above into account. If you don't have time to do this we can merge as-is and open an issue on it.

**Comment by jeromekelleher** [comment]
Merging this PR and opening an issue to address the outstanding issues.

**Pull request merged**
