### PR TITLE
Cache num(Un)AlignedBases for ReadGroupSets

### PR DESCRIPTION
**Pull request by dcolligan**
Issue #1129

### CODE REVIEW

**Comment by dcolligan** [comment]
Actually, I can put the `getStats` method in the abstract base class and do some refactoring of `toProtocolElement`...

**Comment by dcolligan** [comment]
@jeromekelleher ok, ready for review

**Comment by jeromekelleher** [comment]
Nice, +1.

**Comment by jeromekelleher** [comment]
Can you rebase and merge this please @dcolligan?

**Pull request merged**
